
import type { Station, MetroLine } from '@/types';

export const stations: Record<string, Station> = {
    // Red Line
    'shaheed-sthal': { id: 'shaheed-sthal', name: 'Shaheed Sthal (New Bus Adda)', coordinates: { lat: 28.6929, lng: 77.4338 }, lines: ['red'] },
    'hindon-river': { id: 'hindon-river', name: 'Hindon River', coordinates: { lat: 28.6888, lng: 77.4245 }, lines: ['red'] },
    'arthala': { id: 'arthala', name: 'Arthala', coordinates: { lat: 28.6845, lng: 77.4162 }, lines: ['red'] },
    'mohan-nagar': { id: 'mohan-nagar', name: 'Mohan Nagar', coordinates: { lat: 28.6791, lng: 77.4082 }, lines: ['red'] },
    'shyam-park': { id: 'shyam-park', name: 'Shyam Park', coordinates: { lat: 28.6753, lng: 77.3995 }, lines: ['red'] },
    'major-mohit-sharma-rajendra-nagar': { id: 'major-mohit-sharma-rajendra-nagar', name: 'Major Mohit Sharma Rajendra Nagar', coordinates: { lat: 28.6719, lng: 77.3879 }, lines: ['red'] },
    'raj-bagh': { id: 'raj-bagh', name: 'Raj Bagh', coordinates: { lat: 28.6693, lng: 77.3762 }, lines: ['red'] },
    'shaheed-nagar': { id: 'shaheed-nagar', name: 'Shaheed Nagar', coordinates: { lat: 28.6664, lng: 77.3621 }, lines: ['red'] },
    'dilshad-garden': { id: 'dilshad-garden', name: 'Dilshad Garden', coordinates: { lat: 28.6850, lng: 77.3200 }, lines: ['red'] },
    'jhilmil': { id: 'jhilmil', name: 'Jhilmil', coordinates: { lat: 28.6780, lng: 77.3060 }, lines: ['red'] },
    'mansarovar-park': { id: 'mansarovar-park', name: 'Mansarovar Park', coordinates: { lat: 28.6735, lng: 77.2942 }, lines: ['red'] },
    'shahdara': { id: 'shahdara', name: 'Shahdara', coordinates: { lat: 28.6738, lng: 77.2840 }, lines: ['red'] },
    'welcome': { id: 'welcome', name: 'Welcome', coordinates: { lat: 28.6735, lng: 77.2740 }, lines: ['red', 'pink'] },
    'seelampur': { id: 'seelampur', name: 'Seelampur', coordinates: { lat: 28.6732, lng: 77.2625 }, lines: ['red'] },
    'shastri-park': { id: 'shastri-park', name: 'Shastri Park', coordinates: { lat: 28.6720, lng: 77.2470 }, lines: ['red'] },
    'kashmere-gate': { id: 'kashmere-gate', name: 'Kashmere Gate', coordinates: { lat: 28.6655, lng: 77.2290 }, lines: ['red', 'yellow', 'violet'] },
    'tis-hazari': { id: 'tis-hazari', name: 'Tis Hazari', coordinates: { lat: 28.6630, lng: 77.2200 }, lines: ['red'] },
    'pul-bangash': { id: 'pul-bangash', name: 'Pul Bangash', coordinates: { lat: 28.6660, lng: 77.2130 }, lines: ['red'] },
    'pratap-nagar': { id: 'pratap-nagar', name: 'Pratap Nagar', coordinates: { lat: 28.6690, lng: 77.2040 }, lines: ['red'] },
    'shastri-nagar': { id: 'shastri-nagar', name: 'Shastri Nagar', coordinates: { lat: 28.6710, lng: 77.1950 }, lines: ['red'] },
    'inderlok': { id: 'inderlok', name: 'Inderlok', coordinates: { lat: 28.6740, lng: 77.1850 }, lines: ['red', 'green'] },
    'kanhaiya-nagar': { id: 'kanhaiya-nagar', name: 'Kanhaiya Nagar', coordinates: { lat: 28.6790, lng: 77.1790 }, lines: ['red'] },
    'keshav-puram': { id: 'keshav-puram', name: 'Keshav Puram', coordinates: { lat: 28.6820, lng: 77.1700 }, lines: ['red'] },
    'netaji-subhash-place': { id: 'netaji-subhash-place', name: 'Netaji Subhash Place', coordinates: { lat: 28.6870, lng: 77.1600 }, lines: ['red', 'pink'] },
    'kohat-enclave': { id: 'kohat-enclave', name: 'Kohat Enclave', coordinates: { lat: 28.6920, lng: 77.1510 }, lines: ['red'] },
    'pitampura': { id: 'pitampura', name: 'Pitampura', coordinates: { lat: 28.6990, lng: 77.1430 }, lines: ['red'] },
    'rohini-east': { id: 'rohini-east', name: 'Rohini East', coordinates: { lat: 28.7070, lng: 77.1290 }, lines: ['red'] },
    'rohini-west': { id: 'rohini-west', name: 'Rohini West', coordinates: { lat: 28.7110, lng: 77.1190 }, lines: ['red'] },
    'rithala': { id: 'rithala', name: 'Rithala', coordinates: { lat: 28.7160, lng: 77.1080 }, lines: ['red'] },

    // Yellow Line
    'samaypur-badli': { id: 'samaypur-badli', name: 'Samaypur Badli', coordinates: { lat: 28.7450, lng: 77.1640 }, lines: ['yellow'] },
    'rohini-sector-18-19': { id: 'rohini-sector-18-19', name: 'Rohini Sector 18, 19', coordinates: { lat: 28.7350, lng: 77.1660 }, lines: ['yellow'] },
    'haiderpur-badli-mor': { id: 'haiderpur-badli-mor', name: 'Haiderpur Badli Mor', coordinates: { lat: 28.7290, lng: 77.1670 }, lines: ['yellow'] },
    'jahangirpuri': { id: 'jahangirpuri', name: 'Jahangirpuri', coordinates: { lat: 28.7230, lng: 77.1680 }, lines: ['yellow'] },
    'adarsh-nagar': { id: 'adarsh-nagar', name: 'Adarsh Nagar', coordinates: { lat: 28.7150, lng: 77.1750 }, lines: ['yellow'] },
    'azadpur': { id: 'azadpur', name: 'Azadpur', coordinates: { lat: 28.7050, lng: 77.1850 }, lines: ['yellow', 'pink', 'magenta'] },
    'model-town': { id: 'model-town', name: 'Model Town', coordinates: { lat: 28.6990, lng: 77.1930 }, lines: ['yellow'] },
    'guru-tegh-bahadur-nagar': { id: 'guru-tegh-bahadur-nagar', name: 'Guru Tegh Bahadur Nagar', coordinates: { lat: 28.6910, lng: 77.2050 }, lines: ['yellow'] },
    'viswavidyalaya': { id: 'viswavidyalaya', name: 'Vishwavidyalaya', coordinates: { lat: 28.6880, lng: 77.2120 }, lines: ['yellow'] },
    'vidhan-sabha': { id: 'vidhan-sabha', name: 'Vidhan Sabha', coordinates: { lat: 28.6820, lng: 77.2180 }, lines: ['yellow'] },
    'civil-lines': { id: 'civil-lines', name: 'Civil Lines', coordinates: { lat: 28.6750, lng: 77.2240 }, lines: ['yellow'] },
    'chandni-chowk': { id: 'chandni-chowk', name: 'Chandni Chowk', coordinates: { lat: 28.6560, lng: 77.2290 }, lines: ['yellow'] },
    'new-delhi': { id: 'new-delhi', name: 'New Delhi', coordinates: { lat: 28.6420, lng: 77.2210 }, lines: ['yellow', 'airport'] },
    'rajiv-chowk': { id: 'rajiv-chowk', name: 'Rajiv Chowk', coordinates: { lat: 28.6330, lng: 77.2160 }, lines: ['yellow', 'blue'] },
    'patel-chowk': { id: 'patel-chowk', name: 'Patel Chowk', coordinates: { lat: 28.6240, lng: 77.2150 }, lines: ['yellow'] },
    'central-secretariat': { id: 'central-secretariat', name: 'Central Secretariat', coordinates: { lat: 28.6140, lng: 77.2140 }, lines: ['yellow', 'violet'] },
    'udyog-bhawan': { id: 'udyog-bhawan', name: 'Udyog Bhawan', coordinates: { lat: 28.6100, lng: 77.2160 }, lines: ['yellow'] },
    'lok-kalyan-marg': { id: 'lok-kalyan-marg', name: 'Lok Kalyan Marg', coordinates: { lat: 28.5990, lng: 77.2150 }, lines: ['yellow'] },
    'jor-bagh': { id: 'jor-bagh', name: 'Jor Bagh', coordinates: { lat: 28.5860, lng: 77.2170 }, lines: ['yellow'] },
    'dilli-haat-ina': { id: 'dilli-haat-ina', name: 'Dilli Haat - INA', coordinates: { lat: 28.5740, lng: 77.2190 }, lines: ['yellow', 'pink'] },
    'aiims': { id: 'aiims', name: 'AIIMS', coordinates: { lat: 28.5660, lng: 77.2120 }, lines: ['yellow'] },
    'green-park': { id: 'green-park', name: 'Green Park', coordinates: { lat: 28.5580, lng: 77.2060 }, lines: ['yellow'] },
    'hauz-khas': { id: 'hauz-khas', name: 'Hauz Khas', coordinates: { lat: 28.5440, lng: 77.2060 }, lines: ['yellow', 'magenta'] },
    'malviya-nagar': { id: 'malviya-nagar', name: 'Malviya Nagar', coordinates: { lat: 28.5350, lng: 77.2110 }, lines: ['yellow'] },
    'saket': { id: 'saket', name: 'Saket', coordinates: { lat: 28.5240, lng: 77.2160 }, lines: ['yellow'] },
    'qutab-minar': { id: 'qutab-minar', name: 'Qutab Minar', coordinates: { lat: 28.5140, lng: 77.1900 }, lines: ['yellow'] },
    'chhatarpur': { id: 'chhatarpur', name: 'Chhatarpur', coordinates: { lat: 28.5020, lng: 77.1850 }, lines: ['yellow'] },
    'sultanpur': { id: 'sultanpur', name: 'Sultanpur', coordinates: { lat: 28.4950, lng: 77.1720 }, lines: ['yellow'] },
    'ghitorni': { id: 'ghitorni', name: 'Ghitorni', coordinates: { lat: 28.4890, lng: 77.1610 }, lines: ['yellow'] },
    'arjan-garh': { id: 'arjan-garh', name: 'Arjan Garh', coordinates: { lat: 28.4810, lng: 77.1450 }, lines: ['yellow'] },
    'guru-dronacharya': { id: 'guru-dronacharya', name: 'Guru Dronacharya', coordinates: { lat: 28.4830, lng: 77.0940 }, lines: ['yellow'] },
    'sikandarpur': { id: 'sikandarpur', name: 'Sikandarpur', coordinates: { lat: 28.4790, lng: 77.0900 }, lines: ['yellow', 'rapid'] },
    'mg-road': { id: 'mg-road', name: 'MG Road', coordinates: { lat: 28.4750, lng: 77.0810 }, lines: ['yellow'] },
    'iffco-chowk': { id: 'iffco-chowk', name: 'IFFCO Chowk', coordinates: { lat: 28.4680, lng: 77.0720 }, lines: ['yellow'] },
    'millennium-city-centre': { id: 'millennium-city-centre', name: 'Millennium City Centre Gurugram', coordinates: { lat: 28.4590, lng: 77.0710 }, lines: ['yellow'] },

    // Blue Line
    'noida-electronic-city': { id: 'noida-electronic-city', name: 'Noida Electronic City', coordinates: { lat: 28.6345, lng: 77.3712 }, lines: ['blue'] },
    'noida-sector-62': { id: 'noida-sector-62', name: 'Noida Sector 62', coordinates: { lat: 28.6295, lng: 77.3648 }, lines: ['blue'] },
    'noida-sector-59': { id: 'noida-sector-59', name: 'Noida Sector 59', coordinates: { lat: 28.6183, lng: 77.3615 }, lines: ['blue'] },
    'noida-sector-61': { id: 'noida-sector-61', name: 'Noida Sector 61', coordinates: { lat: 28.6074, lng: 77.3591 }, lines: ['blue'] },
    'noida-sector-52': { id: 'noida-sector-52', name: 'Noida Sector 52', coordinates: { lat: 28.5960, lng: 77.3575 }, lines: ['blue', 'aqua'] },
    'noida-sector-34': { id: 'noida-sector-34', name: 'Noida Sector 34', coordinates: { lat: 28.5868, lng: 77.3508 }, lines: ['blue'] },
    'noida-city-centre': { id: 'noida-city-centre', name: 'Noida City Centre', coordinates: { lat: 28.5770, lng: 77.3370 }, lines: ['blue'] },
    'golf-course': { id: 'golf-course', name: 'Golf Course', coordinates: { lat: 28.5700, lng: 77.3220 }, lines: ['blue'] },
    'botanical-garden': { id: 'botanical-garden', name: 'Botanical Garden', coordinates: { lat: 28.5630, lng: 77.3150 }, lines: ['blue', 'magenta'] },
    'noida-sector-18': { id: 'noida-sector-18', name: 'Noida Sector 18', coordinates: { lat: 28.5710, lng: 77.3240 }, lines: ['blue'] },
    'noida-sector-16': { id: 'noida-sector-16', name: 'Noida Sector 16', coordinates: { lat: 28.5800, lng: 77.3090 }, lines: ['blue'] },
    'noida-sector-15': { id: 'noida-sector-15', name: 'Noida Sector 15', coordinates: { lat: 28.5870, lng: 77.3040 }, lines: ['blue'] },
    'new-ashok-nagar': { id: 'new-ashok-nagar', name: 'New Ashok Nagar', coordinates: { lat: 28.5920, lng: 77.2970 }, lines: ['blue'] },
    'mayur-vihar-extension': { id: 'mayur-vihar-extension', name: 'Mayur Vihar Extension', coordinates: { lat: 28.5960, lng: 77.2910 }, lines: ['blue'] },
    'mayur-vihar-i': { id: 'mayur-vihar-i', name: 'Mayur Vihar-I', coordinates: { lat: 28.6010, lng: 77.2880 }, lines: ['blue', 'pink'] },
    'akshardham': { id: 'akshardham', name: 'Akshardham', coordinates: { lat: 28.6180, lng: 77.2780 }, lines: ['blue'] },
    'yamuna-bank': { id: 'yamuna-bank', name: 'Yamuna Bank', coordinates: { lat: 28.6260, lng: 77.2760 }, lines: ['blue'] },
    'indraprastha': { id: 'indraprastha', name: 'Indraprastha', coordinates: { lat: 28.6300, lng: 77.2530 }, lines: ['blue'] },
    'pragati-maidan': { id: 'pragati-maidan', name: 'Pragati Maidan', coordinates: { lat: 28.6280, lng: 77.2410 }, lines: ['blue'] },
    'mandi-house': { id: 'mandi-house', name: 'Mandi House', coordinates: { lat: 28.6270, lng: 77.2340 }, lines: ['blue', 'violet'] },
    'barakhamba-road': { id: 'barakhamba-road', name: 'Barakhamba Road', coordinates: { lat: 28.6310, lng: 77.2280 }, lines: ['blue'] },
    'rk-ashram-marg': { id: 'rk-ashram-marg', name: 'RK Ashram Marg', coordinates: { lat: 28.6430, lng: 77.2060 }, lines: ['blue'] },
    'jhandewalan': { id: 'jhandewalan', name: 'Jhandewalan', coordinates: { lat: 28.6450, lng: 77.1990 }, lines: ['blue'] },
    'karol-bagh': { id: 'karol-bagh', name: 'Karol Bagh', coordinates: { lat: 28.6480, lng: 77.1910 }, lines: ['blue'] },
    'rajendra-place': { id: 'rajendra-place', name: 'Rajendra Place', coordinates: { lat: 28.6490, lng: 77.1790 }, lines: ['blue'] },
    'patel-nagar': { id: 'patel-nagar', name: 'Patel Nagar', coordinates: { lat: 28.6510, lng: 77.1710 }, lines: ['blue'] },
    'shadipur': { id: 'shadipur', name: 'Shadipur', coordinates: { lat: 28.6540, lng: 77.1640 }, lines: ['blue'] },
    'kirti-nagar': { id: 'kirti-nagar', name: 'Kirti Nagar', coordinates: { lat: 28.6560, lng: 77.1580 }, lines: ['blue', 'green'] },
    'moti-nagar': { id: 'moti-nagar', name: 'Moti Nagar', coordinates: { lat: 28.6590, lng: 77.1480 }, lines: ['blue'] },
    'ramesh-nagar': { id: 'ramesh-nagar', name: 'Ramesh Nagar', coordinates: { lat: 28.6620, lng: 77.1390 }, lines: ['blue'] },
    'rajouri-garden': { id: 'rajouri-garden', name: 'Rajouri Garden', coordinates: { lat: 28.6470, lng: 77.1260 }, lines: ['blue', 'pink'] },
    'tagore-garden': { id: 'tagore-garden', name: 'Tagore Garden', coordinates: { lat: 28.6410, lng: 77.1170 }, lines: ['blue'] },
    'subhash-nagar': { id: 'subhash-nagar', name: 'Subhash Nagar', coordinates: { lat: 28.6350, lng: 77.1080 }, lines: ['blue'] },
    'tilak-nagar': { id: 'tilak-nagar', name: 'Tilak Nagar', coordinates: { lat: 28.6310, lng: 77.0980 }, lines: ['blue'] },
    'janakpuri-east': { id: 'janakpuri-east', name: 'Janakpuri East', coordinates: { lat: 28.6290, lng: 77.0890 }, lines: ['blue'] },
    'janakpuri-west': { id: 'janakpuri-west', name: 'Janakpuri West', coordinates: { lat: 28.6290, lng: 77.0800 }, lines: ['blue', 'magenta'] },
    'uttam-nagar-east': { id: 'uttam-nagar-east', name: 'Uttam Nagar East', coordinates: { lat: 28.6250, lng: 77.0690 }, lines: ['blue'] },
    'uttam-nagar-west': { id: 'uttam-nagar-west', name: 'Uttam Nagar West', coordinates: { lat: 28.6220, lng: 77.0600 }, lines: ['blue'] },
    'nawada': { id: 'nawada', name: 'Nawada', coordinates: { lat: 28.6180, lng: 77.0520 }, lines: ['blue'] },
    'dwarka-mor': { id: 'dwarka-mor', name: 'Dwarka Mor', coordinates: { lat: 28.6160, lng: 77.0430 }, lines: ['blue'] },
    'dwarka': { id: 'dwarka', name: 'Dwarka', coordinates: { lat: 28.6120, lng: 77.0360 }, lines: ['grey', 'blue'] },
    'dwarka-sector-14': { id: 'dwarka-sector-14', name: 'Dwarka Sector 14', coordinates: { lat: 28.6080, lng: 77.0280 }, lines: ['blue'] },
    'dwarka-sector-13': { id: 'dwarka-sector-13', name: 'Dwarka Sector 13', coordinates: { lat: 28.6010, lng: 77.0290 }, lines: ['blue'] },
    'dwarka-sector-12': { id: 'dwarka-sector-12', name: 'Dwarka Sector 12', coordinates: { lat: 28.5930, lng: 77.0330 }, lines: ['blue'] },
    'dwarka-sector-11': { id: 'dwarka-sector-11', name: 'Dwarka Sector 11', coordinates: { lat: 28.5850, lng: 77.0390 }, lines: ['blue'] },
    'dwarka-sector-10': { id: 'dwarka-sector-10', name: 'Dwarka Sector 10', coordinates: { lat: 28.5770, lng: 77.0450 }, lines: ['blue'] },
    'dwarka-sector-9': { id: 'dwarka-sector-9', name: 'Dwarka Sector 9', coordinates: { lat: 28.5690, lng: 77.0510 }, lines: ['blue'] },
    'dwarka-sector-8': { id: 'dwarka-sector-8', name: 'Dwarka Sector 8', coordinates: { lat: 28.5610, lng: 77.0560 }, lines: ['blue'] },
    'dwarka-sector-21': { id: 'dwarka-sector-21', name: 'Dwarka Sector 21', coordinates: { lat: 28.5510, lng: 77.0580 }, lines: ['blue', 'airport'] },
    'vaishali': { id: 'vaishali', name: 'Vaishali', coordinates: { lat: 28.6430, lng: 77.3410 }, lines: ['blue'] },
    'kaushambi': { id: 'kaushambi', name: 'Kaushambi', coordinates: { lat: 28.6460, lng: 77.3270 }, lines: ['blue'] },
    'anand-vihar': { id: 'anand-vihar', name: 'Anand Vihar', coordinates: { lat: 28.6480, lng: 77.3150 }, lines: ['blue', 'pink'] },
    'karkarduma': { id: 'karkarduma', name: 'Karkarduma', coordinates: { lat: 28.6490, lng: 77.3050 }, lines: ['blue', 'pink'] },
    'preet-vihar': { id: 'preet-vihar', name: 'Preet Vihar', coordinates: { lat: 28.6450, lng: 77.2940 }, lines: ['blue'] },
    'nirman-vihar': { id: 'nirman-vihar', name: 'Nirman Vihar', coordinates: { lat: 28.6400, lng: 77.2870 }, lines: ['blue'] },
    'laxmi-nagar': { id: 'laxmi-nagar', name: 'Laxmi Nagar', coordinates: { lat: 28.6350, lng: 77.2810 }, lines: ['blue'] },

    // Green Line
    'brigadier-hoshiar-singh': { id: 'brigadier-hoshiar-singh', name: 'Brigadier Hoshiar Singh', coordinates: { lat: 28.6020, lng: 76.9530 }, lines: ['green'] },
    'bahadurgarh-city': { id: 'bahadurgarh-city', name: 'Bahadurgarh City', coordinates: { lat: 28.6380, lng: 76.9400 }, lines: ['green'] },
    'pandit-shree-ram-sharma': { id: 'pandit-shree-ram-sharma', name: 'Pandit Shree Ram Sharma', coordinates: { lat: 28.6530, lng: 76.9590 }, lines: ['green'] },
    'tikri-border': { id: 'tikri-border', name: 'Tikri Border', coordinates: { lat: 28.6600, lng: 76.9740 }, lines: ['green'] },
    'tikri-kalan': { id: 'tikri-kalan', name: 'Tikri Kalan', coordinates: { lat: 28.6650, lng: 76.9890 }, lines: ['green'] },
    'gherwa-metro-station': { id: 'gherwa-metro-station', name: 'Ghevra Metro station', coordinates: { lat: 28.6750, lng: 77.0040 }, lines: ['green'] },
    'mundka-industrial-area': { id: 'mundka-industrial-area', name: 'Mundka Industrial Area', coordinates: { lat: 28.6790, lng: 77.0200 }, lines: ['green'] },
    'mundka': { id: 'mundka', name: 'Mundka', coordinates: { lat: 28.6820, lng: 77.0370 }, lines: ['green'] },
    'rajdhani-park': { id: 'rajdhani-park', name: 'Rajdhani Park', coordinates: { lat: 28.6850, lng: 77.0540 }, lines: ['green'] },
    'nangloi-railway-station': { id: 'nangloi-railway-station', name: 'Nangloi Railway Station', coordinates: { lat: 28.6870, lng: 77.0670 }, lines: ['green'] },
    'nangloi': { id: 'nangloi', name: 'Nangloi', coordinates: { lat: 28.6880, lng: 77.0790 }, lines: ['green'] },
    'surajmal-stadium': { id: 'surajmal-stadium', name: 'Surajmal Stadium', coordinates: { lat: 28.6850, lng: 77.0930 }, lines: ['green'] },
    'udyog-nagar': { id: 'udyog-nagar', name: 'Udyog Nagar', coordinates: { lat: 28.6810, lng: 77.1080 }, lines: ['green'] },
    'peeragarhi': { id: 'peeragarhi', name: 'Peeragarhi', coordinates: { lat: 28.6770, lng: 77.1230 }, lines: ['green'] },
    'paschim-vihar-west': { id: 'paschim-vihar-west', name: 'Paschim Vihar West', coordinates: { lat: 28.6750, lng: 77.1350 }, lines: ['green'] },
    'paschim-vihar-east': { id: 'paschim-vihar-east', name: 'Paschim Vihar East', coordinates: { lat: 28.6730, lng: 77.1450 }, lines: ['green'] },
    'madipur': { id: 'madipur', name: 'Madipur', coordinates: { lat: 28.6720, lng: 77.1530 }, lines: ['green'] },
    'shivaji-park': { id: 'shivaji-park', name: 'Shivaji Park', coordinates: { lat: 28.6710, lng: 77.1590 }, lines: ['green'] },
    'punjabi-bagh-west': { id: 'punjabi-bagh-west', name: 'Punjabi Bagh West', coordinates: { lat: 28.6700, lng: 77.1630 }, lines: ['green', 'pink'] },
    'ashok-park-main': { id: 'ashok-park-main', name: 'Ashok Park Main', coordinates: { lat: 28.6710, lng: 77.1650 }, lines: ['green'] },
    'satguru-ram-singh-marg': { id: 'satguru-ram-singh-marg', name: 'Satguru Ram Singh Marg', coordinates: { lat: 28.6610, lng: 77.1610 }, lines: ['green'] },

    // Violet Line
    'raja-nahar-singh': { id: 'raja-nahar-singh', name: 'Raja Nahar Singh (Ballabhgarh)', coordinates: { lat: 28.3810, lng: 77.3210 }, lines: ['violet'] },
    'sant-surdas-sihi': { id: 'sant-surdas-sihi', name: 'Sant Surdas (SIHI)', coordinates: { lat: 28.3910, lng: 77.3190 }, lines: ['violet'] },
    'escorts-mujesar': { id: 'escorts-mujesar', name: 'Escorts Mujesar', coordinates: { lat: 28.4010, lng: 77.3170 }, lines: ['violet'] },
    'bata-chowk': { id: 'bata-chowk', name: 'Bata Chowk', coordinates: { lat: 28.4110, lng: 77.3150 }, lines: ['violet'] },
    'neelam-chowk-ajronda': { id: 'neelam-chowk-ajronda', name: 'Neelam Chowk Ajronda', coordinates: { lat: 28.4210, lng: 77.3130 }, lines: ['violet'] },
    'old-faridabad': { id: 'old-faridabad', name: 'Old Faridabad', coordinates: { lat: 28.4310, lng: 77.3110 }, lines: ['violet'] },
    'badkhal-mor': { id: 'badkhal-mor', name: 'Badkhal Mor', coordinates: { lat: 28.4410, lng: 77.3090 }, lines: ['violet'] },
    'faridabad-new-town': { id: 'faridabad-new-town', name: 'Faridabad New Town', coordinates: { lat: 28.4510, lng: 77.3070 }, lines: ['violet'] },
    'sarai': { id: 'sarai', name: 'Sarai', coordinates: { lat: 28.4610, lng: 77.3050 }, lines: ['violet'] },
    'nhpc-chowk': { id: 'nhpc-chowk', name: 'NHPC Chowk', coordinates: { lat: 28.4710, lng: 77.3030 }, lines: ['violet'] },
    'mewla-maharajpur': { id: 'mewla-maharajpur', name: 'Mewla Maharajpur', coordinates: { lat: 28.4810, lng: 77.3010 }, lines: ['violet'] },
    'badarpur-border': { id: 'badarpur-border', name: 'Badarpur Border', coordinates: { lat: 28.4910, lng: 77.2990 }, lines: ['violet'] },
    'tughlakabad-station': { id: 'tughlakabad-station', name: 'Tughlakabad Station', coordinates: { lat: 28.5080, lng: 77.2840 }, lines: ['violet'] },
    'mohan-estate': { id: 'mohan-estate', name: 'Mohan Estate', coordinates: { lat: 28.5200, lng: 77.2750 }, lines: ['violet'] },
    'sarita-vihar': { id: 'sarita-vihar', name: 'Sarita Vihar', coordinates: { lat: 28.5300, lng: 77.2700 }, lines: ['violet'] },
    'jasola-apollo': { id: 'jasola-apollo', name: 'Jasola Apollo', coordinates: { lat: 28.5400, lng: 77.2650 }, lines: ['violet'] },
    'okhla': { id: 'okhla', name: 'Okhla', coordinates: { lat: 28.5450, lng: 77.2620 }, lines: ['violet'] },
    'kalkaji-mandir': { id: 'kalkaji-mandir', name: 'Kalkaji Mandir', coordinates: { lat: 28.5490, lng: 77.2590 }, lines: ['violet', 'magenta'] },
    'nehru-place': { id: 'nehru-place', name: 'Nehru Place', coordinates: { lat: 28.5520, lng: 77.2520 }, lines: ['violet'] },
    'kailash-colony': { id: 'kailash-colony', name: 'Kailash Colony', coordinates: { lat: 28.5580, lng: 77.2470 }, lines: ['violet'] },
    'moolchand': { id: 'moolchand', name: 'Moolchand', coordinates: { lat: 28.5630, lng: 77.2440 }, lines: ['violet'] },
    'lajpat-nagar': { id: 'lajpat-nagar', name: 'Lajpat Nagar', coordinates: { lat: 28.5670, lng: 77.2420 }, lines: ['violet', 'pink'] },
    'jangpura': { id: 'jangpura', name: 'Jangpura', coordinates: { lat: 28.5830, lng: 77.2400 }, lines: ['violet'] },
    'jawaharlal-nehru-stadium': { id: 'jawaharlal-nehru-stadium', name: 'Jawaharlal Nehru Stadium', coordinates: { lat: 28.5900, lng: 77.2370 }, lines: ['violet'] },
    'khan-market': { id: 'khan-market', name: 'Khan Market', coordinates: { lat: 28.6000, lng: 77.2270 }, lines: ['violet'] },
    'janpath': { id: 'janpath', name: 'Janpath', coordinates: { lat: 28.6250, lng: 77.2210 }, lines: ['violet'] },
    'ito': { id: 'ito', name: 'ITO', coordinates: { lat: 28.6310, lng: 77.2470 }, lines: ['violet'] },
    'delhi-gate': { id: 'delhi-gate', name: 'Delhi Gate', coordinates: { lat: 28.6430, lng: 77.2400 }, lines: ['violet'] },
    'jama-masjid': { id: 'jama-masjid', name: 'Jama Masjid', coordinates: { lat: 28.6490, lng: 77.2360 }, lines: ['violet'] },
    'lal-qila': { id: 'lal-qila', name: 'Lal Qila', coordinates: { lat: 28.6560, lng: 77.2410 }, lines: ['violet'] },

    // Pink Line
    'shiv-vihar': { id: 'shiv-vihar', name: 'Shiv Vihar', coordinates: { lat: 28.7040, lng: 77.3000 }, lines: ['pink'] },
    'johri-enclave': { id: 'johri-enclave', name: 'Johri Enclave', coordinates: { lat: 28.6970, lng: 77.2970 }, lines: ['pink'] },
    'gokulpuri': { id: 'gokulpuri', name: 'Gokulpuri', coordinates: { lat: 28.6900, lng: 77.2940 }, lines: ['pink'] },
    'jafrabad': { id: 'jafrabad', name: 'Jafrabad', coordinates: { lat: 28.6830, lng: 77.2800 }, lines: ['pink'] },
    'maujpur-babarpur': { id: 'maujpur-babarpur', name: 'Maujpur-Babarpur', coordinates: { lat: 28.6780, lng: 77.2760 }, lines: ['pink'] },
    'east-azad-nagar': { id: 'east-azad-nagar', name: 'East Azad Nagar', coordinates: { lat: 28.6580, lng: 77.2880 }, lines: ['pink'] },
    'krishna-nagar': { id: 'krishna-nagar', name: 'Krishna Nagar', coordinates: { lat: 28.6540, lng: 77.2950 }, lines: ['pink'] },
    'ip-extension': { id: 'ip-extension', name: 'IP Extension', coordinates: { lat: 28.6200, lng: 77.2980 }, lines: ['pink'] },
    'mandawali-west-vinod-nagar': { id: 'mandawali-west-vinod-nagar', name: 'Mandawali - West Vinod Nagar', coordinates: { lat: 28.6250, lng: 77.3050 }, lines: ['pink'] },
    'east-vinod-nagar-mayur-vihar-ii': { id: 'east-vinod-nagar-mayur-vihar-ii', name: 'East Vinod Nagar - Mayur Vihar-II', coordinates: { lat: 28.6150, lng: 77.3100 }, lines: ['pink'] },
    'trilokpuri-sanjay-lake': { id: 'trilokpuri-sanjay-lake', name: 'Trilokpuri Sanjay Lake', coordinates: { lat: 28.6080, lng: 77.3000 }, lines: ['pink'] },
    'vinobapuri': { id: 'vinobapuri', name: 'Vinobapuri', coordinates: { lat: 28.5600, lng: 77.2350 }, lines: ['pink'] },
    'ashram': { id: 'ashram', name: 'Ashram', coordinates: { lat: 28.5700, lng: 77.2550 }, lines: ['pink'] },
    'sarai-kale-khan-nizamuddin': { id: 'sarai-kale-khan-nizamuddin', name: 'Sarai Kale Khan - Nizamuddin', coordinates: { lat: 28.5880, lng: 77.2580 }, lines: ['pink'] },
    'south-extension': { id: 'south-extension', name: 'South Extension', coordinates: { lat: 28.5680, lng: 77.2220 }, lines: ['pink'] },
    'bhikaji-cama-place': { id: 'bhikaji-cama-place', name: 'Bhikaji Cama Place', coordinates: { lat: 28.5720, lng: 77.1950 }, lines: ['pink'] },
    'sir-m-visveswaraya-moti-bagh': { id: 'sir-m-visveswaraya-moti-bagh', name: 'Sir M Vishweshwaraiah Moti Bagh', coordinates: { lat: 28.5800, lng: 77.1850 }, lines: ['pink'] },
    'durgabai-deshmukh-south-campus': { id: 'durgabai-deshmukh-south-campus', name: 'Durgabai Deshmukh South Campus', coordinates: { lat: 28.5900, lng: 77.1750 }, lines: ['pink'] },
    'naraina-vihar': { id: 'naraina-vihar', name: 'Naraina Vihar', coordinates: { lat: 28.6250, lng: 77.1450 }, lines: ['pink'] },
    'mayapuri': { id: 'mayapuri', name: 'Mayapuri', coordinates: { lat: 28.6350, lng: 77.1350 }, lines: ['pink'] },
    'esi-basaidarapur': { id: 'esi-basaidarapur', name: 'ESI-Basaidarapur', coordinates: { lat: 28.6550, lng: 77.1300 }, lines: ['pink'] },
    'punjabi-bagh-east': { id: 'punjabi-bagh-east', name: 'Punjabi Bagh East', coordinates: { lat: 28.6700, lng: 77.1680 }, lines: ['pink'] },
    'shalimar-bagh': { id: 'shalimar-bagh', name: 'Shalimar Bagh', coordinates: { lat: 28.6950, lng: 77.1650 }, lines: ['pink'] },
    'majlis-park': { id: 'majlis-park', name: 'Majlis Park', coordinates: { lat: 28.7180, lng: 77.1720 }, lines: ['pink'] },

    // Magenta Line
    'okhla-bird-sanctuary': { id: 'okhla-bird-sanctuary', name: 'Okhla Bird Sanctuary', coordinates: { lat: 28.5550, lng: 77.3050 }, lines: ['magenta'] },
    'kalindi-kunj': { id: 'kalindi-kunj', name: 'Kalindi Kunj', coordinates: { lat: 28.5450, lng: 77.2950 }, lines: ['magenta'] },
    'jasola-vihar-shaheen-bagh': { id: 'jasola-vihar-shaheen-bagh', name: 'Jasola Vihar Shaheen Bagh', coordinates: { lat: 28.5400, lng: 77.2850 }, lines: ['magenta'] },
    'okhla-vihar': { id: 'okhla-vihar', name: 'Okhla Vihar', coordinates: { lat: 28.5480, lng: 77.2750 }, lines: ['magenta'] },
    'jamia-millia-islamia': { id: 'jamia-millia-islamia', name: 'Jamia Millia Islamia', coordinates: { lat: 28.5550, lng: 77.2700 }, lines: ['magenta'] },
    'sukhdev-vihar': { id: 'sukhdev-vihar', name: 'Sukhdev Vihar', coordinates: { lat: 28.5600, lng: 77.2650 }, lines: ['magenta'] },
    'okhla-nsic': { id: 'okhla-nsic', name: 'Okhla NSIC', coordinates: { lat: 28.5550, lng: 77.2600 }, lines: ['magenta'] },
    'nehru-enclave': { id: 'nehru-enclave', name: 'Nehru Enclave', coordinates: { lat: 28.5500, lng: 77.2550 }, lines: ['magenta'] },
    'greater-kailash': { id: 'greater-kailash', name: 'Greater Kailash', coordinates: { lat: 28.5450, lng: 77.2400 }, lines: ['magenta'] },
    'chirag-delhi': { id: 'chirag-delhi', name: 'Chirag Delhi', coordinates: { lat: 28.5400, lng: 77.2300 }, lines: ['magenta'] },
    'panchsheel-park': { id: 'panchsheel-park', name: 'Panchsheel Park', coordinates: { lat: 28.5420, lng: 77.2200 }, lines: ['magenta'] },
    'iit-delhi': { id: 'iit-delhi', name: 'IIT Delhi', coordinates: { lat: 28.5460, lng: 77.1950 }, lines: ['magenta'] },
    'rk-puram': { id: 'rk-puram', name: 'RK Puram', coordinates: { lat: 28.5580, lng: 77.1800 }, lines: ['magenta'] },
    'munirka': { id: 'munirka', name: 'Munirka', coordinates: { lat: 28.5600, lng: 77.1700 }, lines: ['magenta'] },
    'vasant-vihar': { id: 'vasant-vihar', name: 'Vasant Vihar', coordinates: { lat: 28.5650, lng: 77.1600 }, lines: ['magenta'] },
    'shankar-vihar': { id: 'shankar-vihar', name: 'Shankar Vihar', coordinates: { lat: 28.5700, lng: 77.1500 }, lines: ['magenta'] },
    'terminal-1-igi-airport': { id: 'terminal-1-igi-airport', name: 'Terminal 1-IGI Airport', coordinates: { lat: 28.5520, lng: 77.1230 }, lines: ['magenta'] },
    'sadar-bazar-cantonment': { id: 'sadar-bazar-cantonment', name: 'Sadar Bazar Cantonment', coordinates: { lat: 28.5900, lng: 77.1200 }, lines: ['magenta'] },
    'palam': { id: 'palam', name: 'Palam', coordinates: { lat: 28.5950, lng: 77.1000 }, lines: ['magenta'] },
    'dashrath-puri': { id: 'dashrath-puri', name: 'Dashrath Puri', coordinates: { lat: 28.6050, lng: 77.0900 }, lines: ['magenta'] },
    'dabri-mor-janakpuri-south': { id: 'dabri-mor-janakpuri-south', name: 'Dabri Mor - Janakpuri South', coordinates: { lat: 28.6150, lng: 77.0850 }, lines: ['magenta'] },

    // Airport Express Line
    'igi-airport': { id: 'igi-airport', name: 'IGI Airport', coordinates: { lat: 28.5580, lng: 77.1180 }, lines: ['airport'] },
    'aerocity': { id: 'aerocity', name: 'Aerocity', coordinates: { lat: 28.5470, lng: 77.1210 }, lines: ['airport'] },
    'dhaula-kuan': { id: 'dhaula-kuan', name: 'Dhaula Kuan', coordinates: { lat: 28.5910, lng: 77.1740 }, lines: ['airport'] },
    'shivaji-stadium': { id: 'shivaji-stadium', name: 'Shivaji Stadium', coordinates: { lat: 28.6280, lng: 77.2130 }, lines: ['airport'] },
    'yashobhoomi-dwarka-sector-25': { id: 'yashobhoomi-dwarka-sector-25', name: 'Yashobhoomi Dwarka Sector 25', coordinates: { lat: 28.5500, lng: 77.0300 }, lines: ['airport'] },

    // Aqua Line
    'noida-sector-51': { id: 'noida-sector-51', name: 'Noida Sector 51', coordinates: { lat: 28.5910, lng: 77.3590 }, lines: ['aqua'] },
    'noida-sector-50': { id: 'noida-sector-50', name: 'Noida Sector 50', coordinates: { lat: 28.5830, lng: 77.3620 }, lines: ['aqua'] },
    'noida-sector-76': { id: 'noida-sector-76', name: 'Noida Sector 76', coordinates: { lat: 28.5750, lng: 77.3650 }, lines: ['aqua'] },
    'noida-sector-101': { id: 'noida-sector-101', name: 'Noida Sector 101', coordinates: { lat: 28.5670, lng: 77.3680 }, lines: ['aqua'] },
    'noida-sector-81': { id: 'noida-sector-81', name: 'Noida Sector 81', coordinates: { lat: 28.5590, lng: 77.3710 }, lines: ['aqua'] },
    'nse-sez': { id: 'nse-sez', name: 'NSEZ', coordinates: { lat: 28.5510, lng: 77.3740 }, lines: ['aqua'] },
    'noida-sector-83': { id: 'noida-sector-83', name: 'Noida Sector 83', coordinates: { lat: 28.5430, lng: 77.3770 }, lines: ['aqua'] },
    'noida-sector-137': { id: 'noida-sector-137', name: 'Noida Sector 137', coordinates: { lat: 28.5350, lng: 77.3800 }, lines: ['aqua'] },
    'noida-sector-142': { id: 'noida-sector-142', name: 'Noida Sector 142', coordinates: { lat: 28.5270, lng: 77.3830 }, lines: ['aqua'] },
    'noida-sector-143': { id: 'noida-sector-143', name: 'Noida Sector 143', coordinates: { lat: 28.5190, lng: 77.3860 }, lines: ['aqua'] },
    'noida-sector-144': { id: 'noida-sector-144', name: 'Noida Sector 144', coordinates: { lat: 28.5110, lng: 77.3890 }, lines: ['aqua'] },
    'noida-sector-145': { id: 'noida-sector-145', name: 'Noida Sector 145', coordinates: { lat: 28.5030, lng: 77.3920 }, lines: ['aqua'] },
    'noida-sector-146': { id: 'noida-sector-146', name: 'Noida Sector 146', coordinates: { lat: 28.4950, lng: 77.3950 }, lines: ['aqua'] },
    'noida-sector-147': { id: 'noida-sector-147', name: 'Noida Sector 147', coordinates: { lat: 28.4870, lng: 77.3980 }, lines: ['aqua'] },
    'noida-sector-148': { id: 'noida-sector-148', name: 'Noida Sector 148', coordinates: { lat: 28.4790, lng: 77.4010 }, lines: ['aqua'] },
    'pari-chowk': { id: 'pari-chowk', name: 'Pari Chowk', coordinates: { lat: 28.4650, lng: 77.4850 }, lines: ['aqua'] },
    'alpha-1': { id: 'alpha-1', name: 'Alpha 1', coordinates: { lat: 28.4690, lng: 77.4950 }, lines: ['aqua'] },
    'delta-1': { id: 'delta-1', name: 'Delta 1', coordinates: { lat: 28.4720, lng: 77.5050 }, lines: ['aqua'] },
    'gnida-office': { id: 'gnida-office', name: 'GNIDA Office', coordinates: { lat: 28.4750, lng: 77.5150 }, lines: ['aqua'] },
    'depot-station': { id: 'depot-station', name: 'Depot Station', coordinates: { lat: 28.4680, lng: 77.5130 }, lines: ['aqua'] },

    // Grey Line
    'nangal': { id: 'nangal', name: 'Nangal', coordinates: { lat: 28.6050, lng: 77.0180 }, lines: ['grey'] },
    'najafgarh': { id: 'najafgarh', name: 'Najafgarh', coordinates: { lat: 28.6090, lng: 76.9850 }, lines: ['grey'] },
    'dhansa-bus-stand': { id: 'dhansa-bus-stand', name: 'Dhansa Bus Stand', coordinates: { lat: 28.6060, lng: 76.9170 }, lines: ['grey'] },
    
    // Rapid Metro
    'phase-3': { id: 'phase-3', name: 'Phase 3', coordinates: { lat: 28.5020, lng: 77.0900 }, lines: ['rapid'] },
    'phase-2': { id: 'phase-2', name: 'Phase 2', coordinates: { lat: 28.4950, lng: 77.0880 }, lines: ['rapid'] },
    'belvedere-towers': { id: 'belvedere-towers', name: 'Belvedere Towers', coordinates: { lat: 28.4880, lng: 77.0860 }, lines: ['rapid'] },
    'cyber-city': { id: 'cyber-city', name: 'Cyber City', coordinates: { lat: 28.4820, lng: 77.0840 }, lines: ['rapid'] },
    'moulesari-avenue': { id: 'moulesari-avenue', name: 'Moulsari Avenue', coordinates: { lat: 28.4760, lng: 77.0820 }, lines: ['rapid'] },
    'sector-42-43': { id: 'sector-42-43', name: 'Sector 42-43', coordinates: { lat: 28.4650, lng: 77.0950 }, lines: ['rapid'] },
    'sector-53-54': { id: 'sector-53-54', name: 'Sector 53-54', coordinates: { lat: 28.4550, lng: 77.1050 }, lines: ['rapid'] },
    'sector-54-chowk': { id: 'sector-54-chowk', name: 'Sector 54 Chowk', coordinates: { lat: 28.4450, lng: 77.1100 }, lines: ['rapid'] },
    'sector-55-56': { id: 'sector-55-56', name: 'Sector 55-56', coordinates: { lat: 28.4350, lng: 77.1140 }, lines: ['rapid'] }
};

export const metroLines: MetroLine[] = [
    {
        id: 'red', name: 'Red Line', color: '#ED1C24',
        stations: [
            'shaheed-sthal', 'hindon-river', 'arthala', 'mohan-nagar', 'shyam-park', 
            'major-mohit-sharma-rajendra-nagar', 'raj-bagh', 'shaheed-nagar', 
            'dilshad-garden', 'jhilmil', 'mansarovar-park', 'shahdara', 'welcome', 
            'seelampur', 'shastri-park', 'kashmere-gate', 'tis-hazari', 'pul-bangash', 
            'pratap-nagar', 'shastri-nagar', 'inderlok', 'kanhaiya-nagar', 'keshav-puram', 
            'netaji-subhash-place', 'kohat-enclave', 'pitampura', 'rohini-east', 
            'rohini-west', 'rithala'
        ]
    },
    {
        id: 'yellow', name: 'Yellow Line', color: '#FFD700',
        stations: [
            'samaypur-badli', 'rohini-sector-18-19', 'haiderpur-badli-mor', 'jahangirpuri', 
            'adarsh-nagar', 'azadpur', 'model-town', 'guru-tegh-bahadur-nagar', 
            'viswavidyalaya', 'vidhan-sabha', 'civil-lines', 'kashmere-gate', 
            'chandni-chowk', 'new-delhi', 'rajiv-chowk', 'patel-chowk', 
            'central-secretariat', 'udyog-bhawan', 'lok-kalyan-marg', 'jor-bagh', 
            'dilli-haat-ina', 'aiims', 'green-park', 'hauz-khas', 'malviya-nagar', 
            'saket', 'qutab-minar', 'chhatarpur', 'sultanpur', 'ghitorni', 'arjan-garh', 
            'guru-dronacharya', 'sikandarpur', 'mg-road', 'iffco-chowk', 
            'millennium-city-centre'
        ]
    },
    {
        id: 'blue', name: 'Blue Line (Line 3)', color: '#0055A4',
        stations: [
            'noida-electronic-city', 'noida-sector-62', 'noida-sector-59', 'noida-sector-61',
            'noida-sector-52', 'noida-sector-34', 'noida-city-centre', 'golf-course', 
            'botanical-garden', 'noida-sector-18', 'noida-sector-16', 'noida-sector-15',
            'new-ashok-nagar', 'mayur-vihar-extension', 'mayur-vihar-i', 'akshardham',
            'yamuna-bank', 'indraprastha', 'pragati-maidan', 'mandi-house', 
            'barakhamba-road', 'rajiv-chowk', 'rk-ashram-marg', 'jhandewalan', 'karol-bagh',
            'rajendra-place', 'patel-nagar', 'shadipur', 'kirti-nagar', 'moti-nagar',
            'ramesh-nagar', 'rajouri-garden', 'tagore-garden', 'subhash-nagar', 
            'tilak-nagar', 'janakpuri-east', 'janakpuri-west', 'uttam-nagar-east',
            'uttam-nagar-west', 'nawada', 'dwarka-mor', 'dwarka', 'dwarka-sector-14',
            'dwarka-sector-13', 'dwarka-sector-12', 'dwarka-sector-11', 'dwarka-sector-10',
            'dwarka-sector-9', 'dwarka-sector-8', 'dwarka-sector-21'
        ]
    },
    {
        id: 'blue-branch', name: 'Blue Line Branch (Line 4)', color: '#0055A4',
        stations: [
            'yamuna-bank', 'laxmi-nagar', 'nirman-vihar', 'preet-vihar', 'karkarduma', 
            'anand-vihar', 'kaushambi', 'vaishali'
        ]
    },
    {
        id: 'green', name: 'Green Line', color: '#009B00',
        stations: [
            'brigadier-hoshiar-singh', 'bahadurgarh-city', 'pandit-shree-ram-sharma',
            'tikri-border', 'tikri-kalan', 'gherwa-metro-station', 'mundka-industrial-area',
            'mundka', 'rajdhani-park', 'nangloi-railway-station', 'nangloi', 
            'surajmal-stadium', 'udyog-nagar', 'peeragarhi', 'paschim-vihar-west',
            'paschim-vihar-east', 'madipur', 'shivaji-park', 'punjabi-bagh-west', 
            'ashok-park-main', 'inderlok'
        ]
    },
    {
        id: 'green-branch', name: 'Green Line Branch', color: '#009B00',
        stations: ['ashok-park-main', 'satguru-ram-singh-marg', 'kirti-nagar']
    },
    {
        id: 'violet', name: 'Violet Line', color: '#8A2BE2',
        stations: [
            'kashmere-gate', 'lal-qila', 'jama-masjid', 'delhi-gate', 'ito', 'mandi-house',
            'janpath', 'central-secretariat', 'khan-market', 'jawaharlal-nehru-stadium',
            'jangpura', 'lajpat-nagar', 'moolchand', 'kailash-colony', 'nehru-place',
            'kalkaji-mandir', 'okhla', 'jasola-apollo', 'sarita-vihar', 'mohan-estate',
            'tughlakabad-station', 'badarpur-border', 'sarai', 'nhpc-chowk', 'mewla-maharajpur',
            'faridabad-new-town', 'badkhal-mor', 'old-faridabad', 'neelam-chowk-ajronda',
            'bata-chowk', 'escorts-mujesar', 'sant-surdas-sihi', 'raja-nahar-singh'
        ]
    },
    {
        id: 'pink', name: 'Pink Line', color: '#FF69B4',
        stations: [
            'majlis-park', 'azadpur', 'shalimar-bagh', 'netaji-subhash-place', 
            'punjabi-bagh-west', 'esi-basaidarapur', 'rajouri-garden', 'mayapuri',
            'naraina-vihar', 'durgabai-deshmukh-south-campus', 'sir-m-visveswaraya-moti-bagh',
            'bhikaji-cama-place', 'dilli-haat-ina', 'south-extension', 'lajpat-nagar',
            'vinobapuri', 'ashram', 'sarai-kale-khan-nizamuddin', 'mayur-vihar-i',
            'trilokpuri-sanjay-lake', 'east-vinod-nagar-mayur-vihar-ii',
            'mandawali-west-vinod-nagar', 'ip-extension', 'anand-vihar', 'karkarduma',
            'krishna-nagar', 'east-azad-nagar', 'welcome', 'jafrabad', 'maujpur-babarpur',
            'gokulpuri', 'johri-enclave', 'shiv-vihar'
        ]
    },
    {
        id: 'magenta', name: 'Magenta Line', color: '#FF00FF',
        stations: [
            'janakpuri-west', 'dabri-mor-janakpuri-south', 'dashrath-puri', 'palam',
            'sadar-bazar-cantonment', 'terminal-1-igi-airport', 'shankar-vihar',
            'vasant-vihar', 'munirka', 'rk-puram', 'iit-delhi', 'hauz-khas',
            'panchsheel-park', 'chirag-delhi', 'greater-kailash', 'nehru-enclave',
            'kalkaji-mandir', 'okhla-nsic', 'sukhdev-vihar', 'jamia-millia-islamia',
            'okhla-vihar', 'jasola-vihar-shaheen-bagh', 'kalindi-kunj',
            'okhla-bird-sanctuary', 'botanical-garden'
        ]
    },
    {
        id: 'airport', name: 'Airport Express Line', color: '#FF9933',
        stations: [
            'new-delhi', 'shivaji-stadium', 'dhaula-kuan', 'aerocity', 'igi-airport',
            'dwarka-sector-21', 'yashobhoomi-dwarka-sector-25'
        ]
    },
    {
        id: 'grey', name: 'Grey Line', color: '#808080',
        stations: ['dwarka', 'nangal', 'najafgarh', 'dhansa-bus-stand']
    },
    {
        id: 'aqua', name: 'Aqua Line', color: '#00BFFF',
        stations: [
            'noida-sector-51', 'noida-sector-50', 'noida-sector-76', 'noida-sector-101',
            'noida-sector-81', 'nse-sez', 'noida-sector-83', 'noida-sector-137',
            'noida-sector-142', 'noida-sector-143', 'noida-sector-144', 'noida-sector-145',
            'noida-sector-146', 'noida-sector-147', 'noida-sector-148', 'pari-chowk',
            'alpha-1', 'delta-1', 'gnida-office', 'depot-station'
        ]
    },
    {
        id: 'rapid', name: 'Rapid Metro', color: '#00AEEF',
        stations: [
            'sikandarpur', 'phase-2', 'belvedere-towers', 'cyber-city', 'moulesari-avenue',
            'phase-3', 'sector-42-43', 'sector-53-54', 'sector-54-chowk', 'sector-55-56'
        ]
    }
];
