
import type { Station, MetroLine } from '@/types';

export const stations: Record<string, Station> = {
    // Red Line
    'shaheed-sthal': { id: 'shaheed-sthal', name: 'Shaheed Sthal (New Bus Adda)', coordinates: { lat: 28.693, lng: 77.362 }, lines: ['red'] },
    'hindon-river': { id: 'hindon-river', name: 'Hindon River', coordinates: { lat: 28.689, lng: 77.354 }, lines: ['red'] },
    'arthala': { id: 'arthala', name: 'Arthala', coordinates: { lat: 28.685, lng: 77.346 }, lines: ['red'] },
    'mohan-nagar': { id: 'mohan-nagar', name: 'Mohan Nagar', coordinates: { lat: 28.679, lng: 77.338 }, lines: ['red'] },
    'shyam-park': { id: 'shyam-park', name: 'Shyam Park', coordinates: { lat: 28.675, lng: 77.331 }, lines: ['red'] },
    'major-mohit-sharma-rajendra-nagar': { id: 'major-mohit-sharma-rajendra-nagar', name: 'Major Mohit Sharma Rajendra Nagar', coordinates: { lat: 28.672, lng: 77.325 }, lines: ['red'] },
    'raj-bagh': { id: 'raj-bagh', name: 'Raj Bagh', coordinates: { lat: 28.669, lng: 77.319 }, lines: ['red'] },
    'shaheed-nagar': { id: 'shaheed-nagar', name: 'Shaheed Nagar', coordinates: { lat: 28.666, lng: 77.313 }, lines: ['red'] },
    'dilshad-garden': { id: 'dilshad-garden', name: 'Dilshad Garden', coordinates: { lat: 28.685, lng: 77.318 }, lines: ['red'] },
    'jhilmil': { id: 'jhilmil', name: 'Jhilmil', coordinates: { lat: 28.678, lng: 77.294 }, lines: ['red'] },
    'mansarovar-park': { id: 'mansarovar-park', name: 'Mansarovar Park', coordinates: { lat: 28.674, lng: 77.287 }, lines: ['red'] },
    'shahdara': { id: 'shahdara', name: 'Shahdara', coordinates: { lat: 28.674, lng: 77.281 }, lines: ['red'] },
    'welcome': { id: 'welcome', name: 'Welcome', coordinates: { lat: 28.674, lng: 77.274 }, lines: ['red', 'pink'] },
    'seelampur': { id: 'seelampur', name: 'Seelampur', coordinates: { lat: 28.674, lng: 77.262 }, lines: ['red'] },
    'shastri-park': { id: 'shastri-park', name: 'Shastri Park', coordinates: { lat: 28.672, lng: 77.247 }, lines: ['red'] },
    'kashmere-gate': { id: 'kashmere-gate', name: 'Kashmere Gate', coordinates: { lat: 28.665, lng: 77.229 }, lines: ['red', 'yellow', 'violet'] },
    'tis-hazari': { id: 'tis-hazari', name: 'Tis Hazari', coordinates: { lat: 28.663, lng: 77.220 }, lines: ['red'] },
    'pul-bangash': { id: 'pul-bangash', name: 'Pul Bangash', coordinates: { lat: 28.666, lng: 77.213 }, lines: ['red'] },
    'pratap-nagar': { id: 'pratap-nagar', name: 'Pratap Nagar', coordinates: { lat: 28.669, lng: 77.204 }, lines: ['red'] },
    'shastri-nagar': { id: 'shastri-nagar', name: 'Shastri Nagar', coordinates: { lat: 28.671, lng: 77.195 }, lines: ['red'] },
    'inderlok': { id: 'inderlok', name: 'Inderlok', coordinates: { lat: 28.674, lng: 77.185 }, lines: ['red', 'green'] },
    'kanhaiya-nagar': { id: 'kanhaiya-nagar', name: 'Kanhaiya Nagar', coordinates: { lat: 28.679, lng: 77.179 }, lines: ['red'] },
    'keshav-puram': { id: 'keshav-puram', name: 'Keshav Puram', coordinates: { lat: 28.682, lng: 77.170 }, lines: ['red'] },
    'netaji-subhash-place': { id: 'netaji-subhash-place', name: 'Netaji Subhash Place', coordinates: { lat: 28.687, lng: 77.160 }, lines: ['red', 'pink'] },
    'kohat-enclave': { id: 'kohat-enclave', name: 'Kohat Enclave', coordinates: { lat: 28.692, lng: 77.151 }, lines: ['red'] },
    'pitampura': { id: 'pitampura', name: 'Pitampura', coordinates: { lat: 28.699, lng: 77.143 }, lines: ['red'] },
    'rohini-east': { id: 'rohini-east', name: 'Rohini East', coordinates: { lat: 28.707, lng: 77.129 }, lines: ['red'] },
    'rohini-west': { id: 'rohini-west', name: 'Rohini West', coordinates: { lat: 28.711, lng: 77.119 }, lines: ['red'] },
    'rithala': { id: 'rithala', name: 'Rithala', coordinates: { lat: 28.716, lng: 77.108 }, lines: ['red'] },

    // Yellow Line
    'samaypur-badli': { id: 'samaypur-badli', name: 'Samaypur Badli', coordinates: { lat: 28.745, lng: 77.164 }, lines: ['yellow'] },
    'rohini-sector-18-19': { id: 'rohini-sector-18-19', name: 'Rohini Sector 18, 19', coordinates: { lat: 28.735, lng: 77.166 }, lines: ['yellow'] },
    'haiderpur-badli-mor': { id: 'haiderpur-badli-mor', name: 'Haiderpur Badli Mor', coordinates: { lat: 28.729, lng: 77.167 }, lines: ['yellow'] },
    'jahangirpuri': { id: 'jahangirpuri', name: 'Jahangirpuri', coordinates: { lat: 28.723, lng: 77.168 }, lines: ['yellow'] },
    'adarsh-nagar': { id: 'adarsh-nagar', name: 'Adarsh Nagar', coordinates: { lat: 28.715, lng: 77.175 }, lines: ['yellow'] },
    'azadpur': { id: 'azadpur', name: 'Azadpur', coordinates: { lat: 28.705, lng: 77.185 }, lines: ['yellow', 'pink', 'magenta'] },
    'model-town': { id: 'model-town', name: 'Model Town', coordinates: { lat: 28.699, lng: 77.193 }, lines: ['yellow'] },
    'guru-tegh-bahadur-nagar': { id: 'guru-tegh-bahadur-nagar', name: 'Guru Tegh Bahadur Nagar', coordinates: { lat: 28.691, lng: 77.205 }, lines: ['yellow'] },
    'viswavidyalaya': { id: 'viswavidyalaya', name: 'Vishwavidyalaya', coordinates: { lat: 28.688, lng: 77.212 }, lines: ['yellow'] },
    'vidhan-sabha': { id: 'vidhan-sabha', name: 'Vidhan Sabha', coordinates: { lat: 28.682, lng: 77.218 }, lines: ['yellow'] },
    'civil-lines': { id: 'civil-lines', name: 'Civil Lines', coordinates: { lat: 28.675, lng: 77.224 }, lines: ['yellow'] },
    'chandni-chowk': { id: 'chandni-chowk', name: 'Chandni Chowk', coordinates: { lat: 28.656, lng: 77.229 }, lines: ['yellow'] },
    'new-delhi': { id: 'new-delhi', name: 'New Delhi', coordinates: { lat: 28.642, lng: 77.221 }, lines: ['yellow', 'airport'] },
    'rajiv-chowk': { id: 'rajiv-chowk', name: 'Rajiv Chowk', coordinates: { lat: 28.633, lng: 77.216 }, lines: ['yellow', 'blue'] },
    'patel-chowk': { id: 'patel-chowk', name: 'Patel Chowk', coordinates: { lat: 28.624, lng: 77.215 }, lines: ['yellow'] },
    'central-secretariat': { id: 'central-secretariat', name: 'Central Secretariat', coordinates: { lat: 28.614, lng: 77.214 }, lines: ['yellow', 'violet'] },
    'udyog-bhawan': { id: 'udyog-bhawan', name: 'Udyog Bhawan', coordinates: { lat: 28.610, lng: 77.216 }, lines: ['yellow'] },
    'lok-kalyan-marg': { id: 'lok-kalyan-marg', name: 'Lok Kalyan Marg', coordinates: { lat: 28.599, lng: 77.215 }, lines: ['yellow'] },
    'jor-bagh': { id: 'jor-bagh', name: 'Jor Bagh', coordinates: { lat: 28.586, lng: 77.217 }, lines: ['yellow'] },
    'dilli-haat-ina': { id: 'dilli-haat-ina', name: 'Dilli Haat - INA', coordinates: { lat: 28.574, lng: 77.219 }, lines: ['yellow', 'pink'] },
    'aiims': { id: 'aiims', name: 'AIIMS', coordinates: { lat: 28.566, lng: 77.212 }, lines: ['yellow'] },
    'green-park': { id: 'green-park', name: 'Green Park', coordinates: { lat: 28.558, lng: 77.206 }, lines: ['yellow'] },
    'hauz-khas': { id: 'hauz-khas', name: 'Hauz Khas', coordinates: { lat: 28.544, lng: 77.206 }, lines: ['yellow', 'magenta'] },
    'malviya-nagar': { id: 'malviya-nagar', name: 'Malviya Nagar', coordinates: { lat: 28.535, lng: 77.211 }, lines: ['yellow'] },
    'saket': { id: 'saket', name: 'Saket', coordinates: { lat: 28.524, lng: 77.216 }, lines: ['yellow'] },
    'qutab-minar': { id: 'qutab-minar', name: 'Qutab Minar', coordinates: { lat: 28.514, lng: 77.190 }, lines: ['yellow'] },
    'chhatarpur': { id: 'chhatarpur', name: 'Chhatarpur', coordinates: { lat: 28.502, lng: 77.185 }, lines: ['yellow'] },
    'sultanpur': { id: 'sultanpur', name: 'Sultanpur', coordinates: { lat: 28.495, lng: 77.172 }, lines: ['yellow'] },
    'ghitorni': { id: 'ghitorni', name: 'Ghitorni', coordinates: { lat: 28.489, lng: 77.161 }, lines: ['yellow'] },
    'arjan-garh': { id: 'arjan-garh', name: 'Arjan Garh', coordinates: { lat: 28.481, lng: 77.145 }, lines: ['yellow'] },
    'guru-dronacharya': { id: 'guru-dronacharya', name: 'Guru Dronacharya', coordinates: { lat: 28.483, lng: 77.094 }, lines: ['yellow'] },
    'sikandarpur': { id: 'sikandarpur', name: 'Sikandarpur', coordinates: { lat: 28.479, lng: 77.090 }, lines: ['yellow', 'rapid'] },
    'mg-road': { id: 'mg-road', name: 'MG Road', coordinates: { lat: 28.475, lng: 77.081 }, lines: ['yellow'] },
    'iffco-chowk': { id: 'iffco-chowk', name: 'IFFCO Chowk', coordinates: { lat: 28.468, lng: 77.072 }, lines: ['yellow'] },
    'millennium-city-centre': { id: 'millennium-city-centre', name: 'Millennium City Centre Gurugram', coordinates: { lat: 28.459, lng: 77.071 }, lines: ['yellow'] },

    // Blue Line
    'noida-electronic-city': { id: 'noida-electronic-city', name: 'Noida Electronic City', coordinates: { lat: 28.607, lng: 77.368 }, lines: ['blue'] },
    'noida-sector-62': { id: 'noida-sector-62', name: 'Noida Sector 62', coordinates: { lat: 28.614, lng: 77.364 }, lines: ['blue'] },
    'noida-sector-59': { id: 'noida-sector-59', name: 'Noida Sector 59', coordinates: { lat: 28.603, lng: 77.359 }, lines: ['blue'] },
    'noida-sector-61': { id: 'noida-sector-61', name: 'Noida Sector 61', coordinates: { lat: 28.594, lng: 77.358 }, lines: ['blue'] },
    'noida-sector-52': { id: 'noida-sector-52', name: 'Noida Sector 52', coordinates: { lat: 28.588, lng: 77.358 }, lines: ['blue', 'aqua'] },
    'noida-sector-34': { id: 'noida-sector-34', name: 'Noida Sector 34', coordinates: { lat: 28.581, lng: 77.350 }, lines: ['blue'] },
    'noida-city-centre': { id: 'noida-city-centre', name: 'Noida City Centre', coordinates: { lat: 28.577, lng: 77.327 }, lines: ['blue'] },
    'golf-course': { id: 'golf-course', name: 'Golf Course', coordinates: { lat: 28.570, lng: 77.322 }, lines: ['blue'] },
    'botanical-garden': { id: 'botanical-garden', name: 'Botanical Garden', coordinates: { lat: 28.563, lng: 77.315 }, lines: ['blue', 'magenta'] },
    'noida-sector-18': { id: 'noida-sector-18', name: 'Noida Sector 18', coordinates: { lat: 28.571, lng: 77.324 }, lines: ['blue'] },
    'noida-sector-16': { id: 'noida-sector-16', name: 'Noida Sector 16', coordinates: { lat: 28.580, lng: 77.309 }, lines: ['blue'] },
    'noida-sector-15': { id: 'noida-sector-15', name: 'Noida Sector 15', coordinates: { lat: 28.587, lng: 77.304 }, lines: ['blue'] },
    'new-ashok-nagar': { id: 'new-ashok-nagar', name: 'New Ashok Nagar', coordinates: { lat: 28.592, lng: 77.297 }, lines: ['blue'] },
    'mayur-vihar-extension': { id: 'mayur-vihar-extension', name: 'Mayur Vihar Extension', coordinates: { lat: 28.596, lng: 77.291 }, lines: ['blue'] },
    'mayur-vihar-i': { id: 'mayur-vihar-i', name: 'Mayur Vihar-I', coordinates: { lat: 28.601, lng: 77.288 }, lines: ['blue', 'pink'] },
    'akshardham': { id: 'akshardham', name: 'Akshardham', coordinates: { lat: 28.618, lng: 77.278 }, lines: ['blue'] },
    'yamuna-bank': { id: 'yamuna-bank', name: 'Yamuna Bank', coordinates: { lat: 28.626, lng: 77.276 }, lines: ['blue'] },
    'indraprastha': { id: 'indraprastha', name: 'Indraprastha', coordinates: { lat: 28.630, lng: 77.253 }, lines: ['blue'] },
    'pragati-maidan': { id: 'pragati-maidan', name: 'Pragati Maidan', coordinates: { lat: 28.628, lng: 77.241 }, lines: ['blue'] },
    'mandi-house': { id: 'mandi-house', name: 'Mandi House', coordinates: { lat: 28.627, lng: 77.234 }, lines: ['blue', 'violet'] },
    'barakhamba-road': { id: 'barakhamba-road', name: 'Barakhamba Road', coordinates: { lat: 28.631, lng: 77.228 }, lines: ['blue'] },
    'rk-ashram-marg': { id: 'rk-ashram-marg', name: 'RK Ashram Marg', coordinates: { lat: 28.643, lng: 77.206 }, lines: ['blue'] },
    'jhandewalan': { id: 'jhandewalan', name: 'Jhandewalan', coordinates: { lat: 28.645, lng: 77.199 }, lines: ['blue'] },
    'karol-bagh': { id: 'karol-bagh', name: 'Karol Bagh', coordinates: { lat: 28.648, lng: 77.191 }, lines: ['blue'] },
    'rajendra-place': { id: 'rajendra-place', name: 'Rajendra Place', coordinates: { lat: 28.649, lng: 77.179 }, lines: ['blue'] },
    'patel-nagar': { id: 'patel-nagar', name: 'Patel Nagar', coordinates: { lat: 28.651, lng: 77.171 }, lines: ['blue'] },
    'shadipur': { id: 'shadipur', name: 'Shadipur', coordinates: { lat: 28.654, lng: 77.164 }, lines: ['blue'] },
    'kirti-nagar': { id: 'kirti-nagar', name: 'Kirti Nagar', coordinates: { lat: 28.656, lng: 77.158 }, lines: ['blue', 'green'] },
    'moti-nagar': { id: 'moti-nagar', name: 'Moti Nagar', coordinates: { lat: 28.659, lng: 77.148 }, lines: ['blue'] },
    'ramesh-nagar': { id: 'ramesh-nagar', name: 'Ramesh Nagar', coordinates: { lat: 28.662, lng: 77.139 }, lines: ['blue'] },
    'rajouri-garden': { id: 'rajouri-garden', name: 'Rajouri Garden', coordinates: { lat: 28.647, lng: 77.126 }, lines: ['blue', 'pink'] },
    'tagore-garden': { id: 'tagore-garden', name: 'Tagore Garden', coordinates: { lat: 28.641, lng: 77.117 }, lines: ['blue'] },
    'subhash-nagar': { id: 'subhash-nagar', name: 'Subhash Nagar', coordinates: { lat: 28.635, lng: 77.108 }, lines: ['blue'] },
    'tilak-nagar': { id: 'tilak-nagar', name: 'Tilak Nagar', coordinates: { lat: 28.631, lng: 77.098 }, lines: ['blue'] },
    'janakpuri-east': { id: 'janakpuri-east', name: 'Janakpuri East', coordinates: { lat: 28.629, lng: 77.089 }, lines: ['blue'] },
    'janakpuri-west': { id: 'janakpuri-west', name: 'Janakpuri West', coordinates: { lat: 28.629, lng: 77.080 }, lines: ['blue', 'magenta'] },
    'uttam-nagar-east': { id: 'uttam-nagar-east', name: 'Uttam Nagar East', coordinates: { lat: 28.625, lng: 77.069 }, lines: ['blue'] },
    'uttam-nagar-west': { id: 'uttam-nagar-west', name: 'Uttam Nagar West', coordinates: { lat: 28.622, lng: 77.060 }, lines: ['blue'] },
    'nawada': { id: 'nawada', name: 'Nawada', coordinates: { lat: 28.618, lng: 77.052 }, lines: ['blue'] },
    'dwarka-mor': { id: 'dwarka-mor', name: 'Dwarka Mor', coordinates: { lat: 28.616, lng: 77.043 }, lines: ['blue'] },
    'dwarka': { id: 'dwarka', name: 'Dwarka', coordinates: { lat: 28.586, lng: 77.036 }, lines: ['grey', 'blue'] },
    'dwarka-sector-14': { id: 'dwarka-sector-14', name: 'Dwarka Sector 14', coordinates: { lat: 28.608, lng: 77.028 }, lines: ['blue'] },
    'dwarka-sector-13': { id: 'dwarka-sector-13', name: 'Dwarka Sector 13', coordinates: { lat: 28.601, lng: 77.029 }, lines: ['blue'] },
    'dwarka-sector-12': { id: 'dwarka-sector-12', name: 'Dwarka Sector 12', coordinates: { lat: 28.593, lng: 77.033 }, lines: ['blue'] },
    'dwarka-sector-11': { id: 'dwarka-sector-11', name: 'Dwarka Sector 11', coordinates: { lat: 28.585, lng: 77.039 }, lines: ['blue'] },
    'dwarka-sector-10': { id: 'dwarka-sector-10', name: 'Dwarka Sector 10', coordinates: { lat: 28.577, lng: 77.045 }, lines: ['blue'] },
    'dwarka-sector-9': { id: 'dwarka-sector-9', name: 'Dwarka Sector 9', coordinates: { lat: 28.569, lng: 77.051 }, lines: ['blue'] },
    'dwarka-sector-8': { id: 'dwarka-sector-8', name: 'Dwarka Sector 8', coordinates: { lat: 28.561, lng: 77.056 }, lines: ['blue'] },
    'dwarka-sector-21': { id: 'dwarka-sector-21', name: 'Dwarka Sector 21', coordinates: { lat: 28.551, lng: 77.058 }, lines: ['blue', 'airport'] },
    'vaishali': { id: 'vaishali', name: 'Vaishali', coordinates: { lat: 28.643, lng: 77.341 }, lines: ['blue'] },
    'kaushambi': { id: 'kaushambi', name: 'Kaushambi', coordinates: { lat: 28.646, lng: 77.327 }, lines: ['blue'] },
    'anand-vihar': { id: 'anand-vihar', name: 'Anand Vihar', coordinates: { lat: 28.648, lng: 77.315 }, lines: ['blue', 'pink'] },
    'karkarduma': { id: 'karkarduma', name: 'Karkarduma', coordinates: { lat: 28.649, lng: 77.305 }, lines: ['blue', 'pink'] },
    'preet-vihar': { id: 'preet-vihar', name: 'Preet Vihar', coordinates: { lat: 28.645, lng: 77.294 }, lines: ['blue'] },
    'nirman-vihar': { id: 'nirman-vihar', name: 'Nirman Vihar', coordinates: { lat: 28.640, lng: 77.287 }, lines: ['blue'] },
    'laxmi-nagar': { id: 'laxmi-nagar', name: 'Laxmi Nagar', coordinates: { lat: 28.635, lng: 77.281 }, lines: ['blue'] },

    // Green Line
    'brigadier-hoshiar-singh': { id: 'brigadier-hoshiar-singh', name: 'Brigadier Hoshiar Singh', coordinates: { lat: 28.602, lng: 76.953 }, lines: ['green'] },
    'bahadurgarh-city': { id: 'bahadurgarh-city', name: 'Bahadurgarh City', coordinates: { lat: 28.638, lng: 76.940 }, lines: ['green'] },
    'pandit-shree-ram-sharma': { id: 'pandit-shree-ram-sharma', name: 'Pandit Shree Ram Sharma', coordinates: { lat: 28.653, lng: 76.959 }, lines: ['green'] },
    'tikri-border': { id: 'tikri-border', name: 'Tikri Border', coordinates: { lat: 28.660, lng: 76.974 }, lines: ['green'] },
    'tikri-kalan': { id: 'tikri-kalan', name: 'Tikri Kalan', coordinates: { lat: 28.665, lng: 76.989 }, lines: ['green'] },
    'gherwa-metro-station': { id: 'gherwa-metro-station', name: 'Ghevra Metro station', coordinates: { lat: 28.675, lng: 77.004 }, lines: ['green'] },
    'mundka-industrial-area': { id: 'mundka-industrial-area', name: 'Mundka Industrial Area', coordinates: { lat: 28.679, lng: 77.020 }, lines: ['green'] },
    'mundka': { id: 'mundka', name: 'Mundka', coordinates: { lat: 28.682, lng: 77.037 }, lines: ['green'] },
    'rajdhani-park': { id: 'rajdhani-park', name: 'Rajdhani Park', coordinates: { lat: 28.685, lng: 77.054 }, lines: ['green'] },
    'nangloi-railway-station': { id: 'nangloi-railway-station', name: 'Nangloi Railway Station', coordinates: { lat: 28.687, lng: 77.067 }, lines: ['green'] },
    'nangloi': { id: 'nangloi', name: 'Nangloi', coordinates: { lat: 28.688, lng: 77.079 }, lines: ['green'] },
    'surajmal-stadium': { id: 'surajmal-stadium', name: 'Surajmal Stadium', coordinates: { lat: 28.685, lng: 77.093 }, lines: ['green'] },
    'udyog-nagar': { id: 'udyog-nagar', name: 'Udyog Nagar', coordinates: { lat: 28.681, lng: 77.108 }, lines: ['green'] },
    'peeragarhi': { id: 'peeragarhi', name: 'Peeragarhi', coordinates: { lat: 28.677, lng: 77.123 }, lines: ['green'] },
    'paschim-vihar-west': { id: 'paschim-vihar-west', name: 'Paschim Vihar West', coordinates: { lat: 28.675, lng: 77.135 }, lines: ['green'] },
    'paschim-vihar-east': { id: 'paschim-vihar-east', name: 'Paschim Vihar East', coordinates: { lat: 28.673, lng: 77.145 }, lines: ['green'] },
    'madipur': { id: 'madipur', name: 'Madipur', coordinates: { lat: 28.672, lng: 77.153 }, lines: ['green'] },
    'shivaji-park': { id: 'shivaji-park', name: 'Shivaji Park', coordinates: { lat: 28.671, lng: 77.159 }, lines: ['green'] },
    'punjabi-bagh-west': { id: 'punjabi-bagh-west', name: 'Punjabi Bagh West', coordinates: { lat: 28.670, lng: 77.163 }, lines: ['green', 'pink'] },
    'ashok-park-main': { id: 'ashok-park-main', name: 'Ashok Park Main', coordinates: { lat: 28.671, lng: 77.165 }, lines: ['green'] },
    'satguru-ram-singh-marg': { id: 'satguru-ram-singh-marg', name: 'Satguru Ram Singh Marg', coordinates: { lat: 28.661, lng: 77.161 }, lines: ['green'] },

    // Violet Line
    'raja-nahar-singh': { id: 'raja-nahar-singh', name: 'Raja Nahar Singh (Ballabhgarh)', coordinates: { lat: 28.381, lng: 77.321 }, lines: ['violet'] },
    'sant-surdas-sihi': { id: 'sant-surdas-sihi', name: 'Sant Surdas (SIHI)', coordinates: { lat: 28.391, lng: 77.319 }, lines: ['violet'] },
    'escorts-mujesar': { id: 'escorts-mujesar', name: 'Escorts Mujesar', coordinates: { lat: 28.401, lng: 77.317 }, lines: ['violet'] },
    'bata-chowk': { id: 'bata-chowk', name: 'Bata Chowk', coordinates: { lat: 28.411, lng: 77.315 }, lines: ['violet'] },
    'neelam-chowk-ajronda': { id: 'neelam-chowk-ajronda', name: 'Neelam Chowk Ajronda', coordinates: { lat: 28.421, lng: 77.313 }, lines: ['violet'] },
    'old-faridabad': { id: 'old-faridabad', name: 'Old Faridabad', coordinates: { lat: 28.431, lng: 77.311 }, lines: ['violet'] },
    'badkhal-mor': { id: 'badkhal-mor', name: 'Badkhal Mor', coordinates: { lat: 28.441, lng: 77.309 }, lines: ['violet'] },
    'faridabad-new-town': { id: 'faridabad-new-town', name: 'Faridabad New Town', coordinates: { lat: 28.451, lng: 77.307 }, lines: ['violet'] },
    'sarai': { id: 'sarai', name: 'Sarai', coordinates: { lat: 28.461, lng: 77.305 }, lines: ['violet'] },
    'nhpc-chowk': { id: 'nhpc-chowk', name: 'NHPC Chowk', coordinates: { lat: 28.471, lng: 77.303 }, lines: ['violet'] },
    'mewla-maharajpur': { id: 'mewla-maharajpur', name: 'Mewla Maharajpur', coordinates: { lat: 28.481, lng: 77.301 }, lines: ['violet'] },
    'badarpur-border': { id: 'badarpur-border', name: 'Badarpur Border', coordinates: { lat: 28.491, lng: 77.299 }, lines: ['violet'] },
    'tughlakabad-station': { id: 'tughlakabad-station', name: 'Tughlakabad Station', coordinates: { lat: 28.508, lng: 77.284 }, lines: ['violet'] },
    'mohan-estate': { id: 'mohan-estate', name: 'Mohan Estate', coordinates: { lat: 28.520, lng: 77.275 }, lines: ['violet'] },
    'sarita-vihar': { id: 'sarita-vihar', name: 'Sarita Vihar', coordinates: { lat: 28.530, lng: 77.270 }, lines: ['violet'] },
    'jasola-apollo': { id: 'jasola-apollo', name: 'Jasola Apollo', coordinates: { lat: 28.540, lng: 77.265 }, lines: ['violet'] },
    'okhla': { id: 'okhla', name: 'Okhla', coordinates: { lat: 28.545, lng: 77.262 }, lines: ['violet'] },
    'kalkaji-mandir': { id: 'kalkaji-mandir', name: 'Kalkaji Mandir', coordinates: { lat: 28.549, lng: 77.259 }, lines: ['violet', 'magenta'] },
    'nehru-place': { id: 'nehru-place', name: 'Nehru Place', coordinates: { lat: 28.552, lng: 77.252 }, lines: ['violet'] },
    'kailash-colony': { id: 'kailash-colony', name: 'Kailash Colony', coordinates: { lat: 28.558, lng: 77.247 }, lines: ['violet'] },
    'moolchand': { id: 'moolchand', name: 'Moolchand', coordinates: { lat: 28.563, lng: 77.244 }, lines: ['violet'] },
    'lajpat-nagar': { id: 'lajpat-nagar', name: 'Lajpat Nagar', coordinates: { lat: 28.567, lng: 77.242 }, lines: ['violet', 'pink'] },
    'jangpura': { id: 'jangpura', name: 'Jangpura', coordinates: { lat: 28.583, lng: 77.240 }, lines: ['violet'] },
    'jawaharlal-nehru-stadium': { id: 'jawaharlal-nehru-stadium', name: 'Jawaharlal Nehru Stadium', coordinates: { lat: 28.590, lng: 77.237 }, lines: ['violet'] },
    'khan-market': { id: 'khan-market', name: 'Khan Market', coordinates: { lat: 28.600, lng: 77.227 }, lines: ['violet'] },
    'janpath': { id: 'janpath', name: 'Janpath', coordinates: { lat: 28.625, lng: 77.221 }, lines: ['violet'] },
    'ito': { id: 'ito', name: 'ITO', coordinates: { lat: 28.631, lng: 77.247 }, lines: ['violet'] },
    'delhi-gate': { id: 'delhi-gate', name: 'Delhi Gate', coordinates: { lat: 28.643, lng: 77.240 }, lines: ['violet'] },
    'jama-masjid': { id: 'jama-masjid', name: 'Jama Masjid', coordinates: { lat: 28.649, lng: 77.236 }, lines: ['violet'] },
    'lal-qila': { id: 'lal-qila', name: 'Lal Qila', coordinates: { lat: 28.656, lng: 77.241 }, lines: ['violet'] },

    // Pink Line
    'shiv-vihar': { id: 'shiv-vihar', name: 'Shiv Vihar', coordinates: { lat: 28.704, lng: 77.300 }, lines: ['pink'] },
    'johri-enclave': { id: 'johri-enclave', name: 'Johri Enclave', coordinates: { lat: 28.697, lng: 77.297 }, lines: ['pink'] },
    'gokulpuri': { id: 'gokulpuri', name: 'Gokulpuri', coordinates: { lat: 28.690, lng: 77.294 }, lines: ['pink'] },
    'jafrabad': { id: 'jafrabad', name: 'Jafrabad', coordinates: { lat: 28.683, lng: 77.280 }, lines: ['pink'] },
    'maujpur-babarpur': { id: 'maujpur-babarpur', name: 'Maujpur-Babarpur', coordinates: { lat: 28.678, lng: 77.276 }, lines: ['pink'] },
    'east-azad-nagar': { id: 'east-azad-nagar', name: 'East Azad Nagar', coordinates: { lat: 28.658, lng: 77.288 }, lines: ['pink'] },
    'krishna-nagar': { id: 'krishna-nagar', name: 'Krishna Nagar', coordinates: { lat: 28.654, lng: 77.295 }, lines: ['pink'] },
    'ip-extension': { id: 'ip-extension', name: 'IP Extension', coordinates: { lat: 28.620, lng: 77.298 }, lines: ['pink'] },
    'mandawali-west-vinod-nagar': { id: 'mandawali-west-vinod-nagar', name: 'Mandawali - West Vinod Nagar', coordinates: { lat: 28.625, lng: 77.305 }, lines: ['pink'] },
    'east-vinod-nagar-mayur-vihar-ii': { id: 'east-vinod-nagar-mayur-vihar-ii', name: 'East Vinod Nagar - Mayur Vihar-II', coordinates: { lat: 28.615, lng: 77.310 }, lines: ['pink'] },
    'trilokpuri-sanjay-lake': { id: 'trilokpuri-sanjay-lake', name: 'Trilokpuri Sanjay Lake', coordinates: { lat: 28.608, lng: 77.300 }, lines: ['pink'] },
    'vinobapuri': { id: 'vinobapuri', name: 'Vinobapuri', coordinates: { lat: 28.560, lng: 77.235 }, lines: ['pink'] },
    'ashram': { id: 'ashram', name: 'Ashram', coordinates: { lat: 28.570, lng: 77.255 }, lines: ['pink'] },
    'sarai-kale-khan-nizamuddin': { id: 'sarai-kale-khan-nizamuddin', name: 'Sarai Kale Khan - Nizamuddin', coordinates: { lat: 28.588, lng: 77.258 }, lines: ['pink'] },
    'south-extension': { id: 'south-extension', name: 'South Extension', coordinates: { lat: 28.568, lng: 77.222 }, lines: ['pink'] },
    'bhikaji-cama-place': { id: 'bhikaji-cama-place', name: 'Bhikaji Cama Place', coordinates: { lat: 28.572, lng: 77.195 }, lines: ['pink'] },
    'sir-m-visveswaraya-moti-bagh': { id: 'sir-m-visveswaraya-moti-bagh', name: 'Sir M Vishweshwaraiah Moti Bagh', coordinates: { lat: 28.580, lng: 77.185 }, lines: ['pink'] },
    'durgabai-deshmukh-south-campus': { id: 'durgabai-deshmukh-south-campus', name: 'Durgabai Deshmukh South Campus', coordinates: { lat: 28.590, lng: 77.175 }, lines: ['pink'] },
    'naraina-vihar': { id: 'naraina-vihar', name: 'Naraina Vihar', coordinates: { lat: 28.625, lng: 77.145 }, lines: ['pink'] },
    'mayapuri': { id: 'mayapuri', name: 'Mayapuri', coordinates: { lat: 28.635, lng: 77.135 }, lines: ['pink'] },
    'esi-basaidarapur': { id: 'esi-basaidarapur', name: 'ESI-Basaidarapur', coordinates: { lat: 28.655, lng: 77.130 }, lines: ['pink'] },
    'punjabi-bagh-east': { id: 'punjabi-bagh-east', name: 'Punjabi Bagh East', coordinates: { lat: 28.670, lng: 77.168 }, lines: ['pink'] },
    'shalimar-bagh': { id: 'shalimar-bagh', name: 'Shalimar Bagh', coordinates: { lat: 28.695, lng: 77.165 }, lines: ['pink'] },
    'majlis-park': { id: 'majlis-park', name: 'Majlis Park', coordinates: { lat: 28.718, lng: 77.172 }, lines: ['pink'] },

    // Magenta Line
    'botanical-garden-magenta': { id: 'botanical-garden-magenta', name: 'Botanical Garden', coordinates: { lat: 28.563, lng: 77.315 }, lines: ['magenta', 'blue'] },
    'okhla-bird-sanctuary': { id: 'okhla-bird-sanctuary', name: 'Okhla Bird Sanctuary', coordinates: { lat: 28.555, lng: 77.305 }, lines: ['magenta'] },
    'kalindi-kunj': { id: 'kalindi-kunj', name: 'Kalindi Kunj', coordinates: { lat: 28.545, lng: 77.295 }, lines: ['magenta'] },
    'jasola-vihar-shaheen-bagh': { id: 'jasola-vihar-shaheen-bagh', name: 'Jasola Vihar Shaheen Bagh', coordinates: { lat: 28.540, lng: 77.285 }, lines: ['magenta'] },
    'okhla-vihar': { id: 'okhla-vihar', name: 'Okhla Vihar', coordinates: { lat: 28.548, lng: 77.275 }, lines: ['magenta'] },
    'jamia-millia-islamia': { id: 'jamia-millia-islamia', name: 'Jamia Millia Islamia', coordinates: { lat: 28.555, lng: 77.270 }, lines: ['magenta'] },
    'sukhdev-vihar': { id: 'sukhdev-vihar', name: 'Sukhdev Vihar', coordinates: { lat: 28.560, lng: 77.265 }, lines: ['magenta'] },
    'okhla-nsic': { id: 'okhla-nsic', name: 'Okhla NSIC', coordinates: { lat: 28.555, lng: 77.260 }, lines: ['magenta'] },
    'nehru-enclave': { id: 'nehru-enclave', name: 'Nehru Enclave', coordinates: { lat: 28.550, lng: 77.255 }, lines: ['magenta'] },
    'greater-kailash': { id: 'greater-kailash', name: 'Greater Kailash', coordinates: { lat: 28.545, lng: 77.240 }, lines: ['magenta'] },
    'chirag-delhi': { id: 'chirag-delhi', name: 'Chirag Delhi', coordinates: { lat: 28.540, lng: 77.230 }, lines: ['magenta'] },
    'panchsheel-park': { id: 'panchsheel-park', name: 'Panchsheel Park', coordinates: { lat: 28.542, lng: 77.220 }, lines: ['magenta'] },
    'iit-delhi': { id: 'iit-delhi', name: 'IIT Delhi', coordinates: { lat: 28.546, lng: 77.195 }, lines: ['magenta'] },
    'rk-puram': { id: 'rk-puram', name: 'RK Puram', coordinates: { lat: 28.558, lng: 77.180 }, lines: ['magenta'] },
    'munirka': { id: 'munirka', name: 'Munirka', coordinates: { lat: 28.560, lng: 77.170 }, lines: ['magenta'] },
    'vasant-vihar': { id: 'vasant-vihar', name: 'Vasant Vihar', coordinates: { lat: 28.565, lng: 77.160 }, lines: ['magenta'] },
    'shankar-vihar': { id: 'shankar-vihar', name: 'Shankar Vihar', coordinates: { lat: 28.570, lng: 77.150 }, lines: ['magenta'] },
    'terminal-1-igi-airport': { id: 'terminal-1-igi-airport', name: 'Terminal 1-IGI Airport', coordinates: { lat: 28.552, lng: 77.123 }, lines: ['magenta'] },
    'sadar-bazar-cantonment': { id: 'sadar-bazar-cantonment', name: 'Sadar Bazar Cantonment', coordinates: { lat: 28.590, lng: 77.120 }, lines: ['magenta'] },
    'palam': { id: 'palam', name: 'Palam', coordinates: { lat: 28.595, lng: 77.100 }, lines: ['magenta'] },
    'dashrath-puri': { id: 'dashrath-puri', name: 'Dashrath Puri', coordinates: { lat: 28.605, lng: 77.090 }, lines: ['magenta'] },
    'dabri-mor-janakpuri-south': { id: 'dabri-mor-janakpuri-south', name: 'Dabri Mor - Janakpuri South', coordinates: { lat: 28.615, lng: 77.085 }, lines: ['magenta'] },

    // Airport Express Line
    'igi-airport': { id: 'igi-airport', name: 'IGI Airport', coordinates: { lat: 28.558, lng: 77.118 }, lines: ['airport'] },
    'aerocity': { id: 'aerocity', name: 'Aerocity', coordinates: { lat: 28.547, lng: 77.121 }, lines: ['airport'] },
    'dhaula-kuan': { id: 'dhaula-kuan', name: 'Dhaula Kuan', coordinates: { lat: 28.591, lng: 77.174 }, lines: ['airport'] },
    'shivaji-stadium': { id: 'shivaji-stadium', name: 'Shivaji Stadium', coordinates: { lat: 28.628, lng: 77.213 }, lines: ['airport'] },
    'yashobhoomi-dwarka-sector-25': { id: 'yashobhoomi-dwarka-sector-25', name: 'Yashobhoomi Dwarka Sector 25', coordinates: { lat: 28.550, lng: 77.030 }, lines: ['airport'] },

    // Aqua Line
    'noida-sector-51': { id: 'noida-sector-51', name: 'Noida Sector 51', coordinates: { lat: 28.591, lng: 77.359 }, lines: ['aqua'] },
    'noida-sector-50': { id: 'noida-sector-50', name: 'Noida Sector 50', coordinates: { lat: 28.583, lng: 77.362 }, lines: ['aqua'] },
    'noida-sector-76': { id: 'noida-sector-76', name: 'Noida Sector 76', coordinates: { lat: 28.575, lng: 77.365 }, lines: ['aqua'] },
    'noida-sector-101': { id: 'noida-sector-101', name: 'Noida Sector 101', coordinates: { lat: 28.567, lng: 77.368 }, lines: ['aqua'] },
    'noida-sector-81': { id: 'noida-sector-81', name: 'Noida Sector 81', coordinates: { lat: 28.559, lng: 77.371 }, lines: ['aqua'] },
    'nse-sez': { id: 'nse-sez', name: 'NSEZ', coordinates: { lat: 28.551, lng: 77.374 }, lines: ['aqua'] },
    'noida-sector-83': { id: 'noida-sector-83', name: 'Noida Sector 83', coordinates: { lat: 28.543, lng: 77.377 }, lines: ['aqua'] },
    'noida-sector-137': { id: 'noida-sector-137', name: 'Noida Sector 137', coordinates: { lat: 28.535, lng: 77.380 }, lines: ['aqua'] },
    'noida-sector-142': { id: 'noida-sector-142', name: 'Noida Sector 142', coordinates: { lat: 28.527, lng: 77.383 }, lines: ['aqua'] },
    'noida-sector-143': { id: 'noida-sector-143', name: 'Noida Sector 143', coordinates: { lat: 28.519, lng: 77.386 }, lines: ['aqua'] },
    'noida-sector-144': { id: 'noida-sector-144', name: 'Noida Sector 144', coordinates: { lat: 28.511, lng: 77.389 }, lines: ['aqua'] },
    'noida-sector-145': { id: 'noida-sector-145', name: 'Noida Sector 145', coordinates: { lat: 28.503, lng: 77.392 }, lines: ['aqua'] },
    'noida-sector-146': { id: 'noida-sector-146', name: 'Noida Sector 146', coordinates: { lat: 28.495, lng: 77.395 }, lines: ['aqua'] },
    'noida-sector-147': { id: 'noida-sector-147', name: 'Noida Sector 147', coordinates: { lat: 28.487, lng: 77.398 }, lines: ['aqua'] },
    'noida-sector-148': { id: 'noida-sector-148', name: 'Noida Sector 148', coordinates: { lat: 28.479, lng: 77.401 }, lines: ['aqua'] },
    'pari-chowk': { id: 'pari-chowk', name: 'Pari Chowk', coordinates: { lat: 28.465, lng: 77.485 }, lines: ['aqua'] },
    'alpha-1': { id: 'alpha-1', name: 'Alpha 1', coordinates: { lat: 28.469, lng: 77.495 }, lines: ['aqua'] },
    'delta-1': { id: 'delta-1', name: 'Delta 1', coordinates: { lat: 28.472, lng: 77.505 }, lines: ['aqua'] },
    'gnida-office': { id: 'gnida-office', name: 'GNIDA Office', coordinates: { lat: 28.475, lng: 77.515 }, lines: ['aqua'] },
    'depot-station': { id: 'depot-station', name: 'Depot Station', coordinates: { lat: 28.468, lng: 77.513 }, lines: ['aqua'] },

    // Grey Line
    'nangal': { id: 'nangal', name: 'Nangal', coordinates: { lat: 28.590, lng: 77.015 }, lines: ['grey'] },
    'najafgarh': { id: 'najafgarh', name: 'Najafgarh', coordinates: { lat: 28.598, lng: 76.985 }, lines: ['grey'] },
    'dhansa-bus-stand': { id: 'dhansa-bus-stand', name: 'Dhansa Bus Stand', coordinates: { lat: 28.595, lng: 76.917 }, lines: ['grey'] },
    
    // Rapid Metro
    'phase-3': { id: 'phase-3', name: 'Phase 3', coordinates: { lat: 28.502, lng: 77.090 }, lines: ['rapid'] },
    'phase-2': { id: 'phase-2', name: 'Phase 2', coordinates: { lat: 28.495, lng: 77.088 }, lines: ['rapid'] },
    'belvedere-towers': { id: 'belvedere-towers', name: 'Belvedere Towers', coordinates: { lat: 28.488, lng: 77.086 }, lines: ['rapid'] },
    'cyber-city': { id: 'cyber-city', name: 'Cyber City', coordinates: { lat: 28.482, lng: 77.084 }, lines: ['rapid'] },
    'moulesari-avenue': { id: 'moulesari-avenue', name: 'Moulsari Avenue', coordinates: { lat: 28.476, lng: 77.082 }, lines: ['rapid'] },
    'sector-42-43': { id: 'sector-42-43', name: 'Sector 42-43', coordinates: { lat: 28.465, lng: 77.095 }, lines: ['rapid'] },
    'sector-53-54': { id: 'sector-53-54', name: 'Sector 53-54', coordinates: { lat: 28.455, lng: 77.105 }, lines: ['rapid'] },
    'sector-54-chowk': { id: 'sector-54-chowk', name: 'Sector 54 Chowk', coordinates: { lat: 28.445, lng: 77.110 }, lines: ['rapid'] },
    'sector-55-56': { id: 'sector-55-56', name: 'Sector 55-56', coordinates: { lat: 28.435, lng: 77.114 }, lines: ['rapid'] }
};

export const metroLines: MetroLine[] = [
    {
        id: 'red', name: 'Red Line', color: '#ED1C24',
        stations: [
            'shaheed-sthal', 'hindon-river', 'arthala', 'mohan-nagar', 'shyam-park', 
            'major-mohit-sharma-rajendra-nagar', 'raj-bagh', 'shaheed-nagar', 
            'dilshad-garden', 'jhilmil', 'mansarovar-park', 'shahdara', 'welcome', 
            'seelampur', 'shastri-park', 'kashmere-gate', 'tis-hazari', 'pul-bangash', 
            'pratap-nagar', 'shastri-nagar', 'inderlok', 'kanhaiya-nagar', 'keshav-puram', 
            'netaji-subhash-place', 'kohat-enclave', 'pitampura', 'rohini-east', 
            'rohini-west', 'rithala'
        ]
    },
    {
        id: 'yellow', name: 'Yellow Line', color: '#FFD700',
        stations: [
            'samaypur-badli', 'rohini-sector-18-19', 'haiderpur-badli-mor', 'jahangirpuri', 
            'adarsh-nagar', 'azadpur', 'model-town', 'guru-tegh-bahadur-nagar', 
            'viswavidyalaya', 'vidhan-sabha', 'civil-lines', 'kashmere-gate', 
            'chandni-chowk', 'new-delhi', 'rajiv-chowk', 'patel-chowk', 
            'central-secretariat', 'udyog-bhawan', 'lok-kalyan-marg', 'jor-bagh', 
            'dilli-haat-ina', 'aiims', 'green-park', 'hauz-khas', 'malviya-nagar', 
            'saket', 'qutab-minar', 'chhatarpur', 'sultanpur', 'ghitorni', 'arjan-garh', 
            'guru-dronacharya', 'sikandarpur', 'mg-road', 'iffco-chowk', 
            'millennium-city-centre'
        ]
    },
    {
        id: 'blue', name: 'Blue Line (Line 3)', color: '#0055A4',
        stations: [
            'noida-electronic-city', 'noida-sector-62', 'noida-sector-59', 'noida-sector-61',
            'noida-sector-52', 'noida-sector-34', 'noida-city-centre', 'golf-course', 
            'botanical-garden', 'noida-sector-18', 'noida-sector-16', 'noida-sector-15',
            'new-ashok-nagar', 'mayur-vihar-extension', 'mayur-vihar-i', 'akshardham',
            'yamuna-bank', 'indraprastha', 'pragati-maidan', 'mandi-house', 
            'barakhamba-road', 'rajiv-chowk', 'rk-ashram-marg', 'jhandewalan', 'karol-bagh',
            'rajendra-place', 'patel-nagar', 'shadipur', 'kirti-nagar', 'moti-nagar',
            'ramesh-nagar', 'rajouri-garden', 'tagore-garden', 'subhash-nagar', 
            'tilak-nagar', 'janakpuri-east', 'janakpuri-west', 'uttam-nagar-east',
            'uttam-nagar-west', 'nawada', 'dwarka-mor', 'dwarka', 'dwarka-sector-14',
            'dwarka-sector-13', 'dwarka-sector-12', 'dwarka-sector-11', 'dwarka-sector-10',
            'dwarka-sector-9', 'dwarka-sector-8', 'dwarka-sector-21'
        ]
    },
    {
        id: 'blue-branch', name: 'Blue Line Branch (Line 4)', color: '#0055A4',
        stations: [
            'yamuna-bank', 'laxmi-nagar', 'nirman-vihar', 'preet-vihar', 'karkarduma', 
            'anand-vihar', 'kaushambi', 'vaishali'
        ]
    },
    {
        id: 'green', name: 'Green Line', color: '#009B00',
        stations: [
            'brigadier-hoshiar-singh', 'bahadurgarh-city', 'pandit-shree-ram-sharma',
            'tikri-border', 'tikri-kalan', 'gherwa-metro-station', 'mundka-industrial-area',
            'mundka', 'rajdhani-park', 'nangloi-railway-station', 'nangloi', 
            'surajmal-stadium', 'udyog-nagar', 'peeragarhi', 'paschim-vihar-west',
            'paschim-vihar-east', 'madipur', 'shivaji-park', 'punjabi-bagh-west', 
            'ashok-park-main', 'inderlok'
        ]
    },
    {
        id: 'green-branch', name: 'Green Line Branch', color: '#009B00',
        stations: ['ashok-park-main', 'satguru-ram-singh-marg', 'kirti-nagar']
    },
    {
        id: 'violet', name: 'Violet Line', color: '#8A2BE2',
        stations: [
            'kashmere-gate', 'lal-qila', 'jama-masjid', 'delhi-gate', 'ito', 'mandi-house',
            'janpath', 'central-secretariat', 'khan-market', 'jawaharlal-nehru-stadium',
            'jangpura', 'lajpat-nagar', 'moolchand', 'kailash-colony', 'nehru-place',
            'kalkaji-mandir', 'okhla', 'jasola-apollo', 'sarita-vihar', 'mohan-estate',
            'tughlakabad-station', 'badarpur-border', 'sarai', 'nhpc-chowk', 'mewla-maharajpur',
            'faridabad-new-town', 'badkhal-mor', 'old-faridabad', 'neelam-chowk-ajronda',
            'bata-chowk', 'escorts-mujesar', 'sant-surdas-sihi', 'raja-nahar-singh'
        ]
    },
    {
        id: 'pink', name: 'Pink Line', color: '#FF69B4',
        stations: [
            'majlis-park', 'azadpur', 'shalimar-bagh', 'netaji-subhash-place', 
            'punjabi-bagh-west', 'esi-basaidarapur', 'rajouri-garden', 'mayapuri',
            'naraina-vihar', 'durgabai-deshmukh-south-campus', 'sir-m-visveswaraya-moti-bagh',
            'bhikaji-cama-place', 'dilli-haat-ina', 'south-extension', 'lajpat-nagar',
            'vinobapuri', 'ashram', 'sarai-kale-khan-nizamuddin', 'mayur-vihar-i',
            'trilokpuri-sanjay-lake', 'east-vinod-nagar-mayur-vihar-ii',
            'mandawali-west-vinod-nagar', 'ip-extension', 'anand-vihar', 'karkarduma',
            'krishna-nagar', 'east-azad-nagar', 'welcome', 'jafrabad', 'maujpur-babarpur',
            'gokulpuri', 'johri-enclave', 'shiv-vihar'
        ]
    },
    {
        id: 'magenta', name: 'Magenta Line', color: '#FF00FF',
        stations: [
            'janakpuri-west', 'dabri-mor-janakpuri-south', 'dashrath-puri', 'palam',
            'sadar-bazar-cantonment', 'terminal-1-igi-airport', 'shankar-vihar',
            'vasant-vihar', 'munirka', 'rk-puram', 'iit-delhi', 'hauz-khas',
            'panchsheel-park', 'chirag-delhi', 'greater-kailash', 'nehru-enclave',
            'kalkaji-mandir', 'okhla-nsic', 'sukhdev-vihar', 'jamia-millia-islamia',
            'okhla-vihar', 'jasola-vihar-shaheen-bagh', 'kalindi-kunj',
            'okhla-bird-sanctuary', 'botanical-garden'
        ]
    },
    {
        id: 'airport', name: 'Airport Express Line', color: '#FF9933',
        stations: [
            'new-delhi', 'shivaji-stadium', 'dhaula-kuan', 'aerocity', 'igi-airport',
            'dwarka-sector-21', 'yashobhoomi-dwarka-sector-25'
        ]
    },
    {
        id: 'grey', name: 'Grey Line', color: '#808080',
        stations: ['dwarka', 'nangal', 'najafgarh', 'dhansa-bus-stand']
    },
    {
        id: 'aqua', name: 'Aqua Line', color: '#00BFFF',
        stations: [
            'noida-sector-51', 'noida-sector-50', 'noida-sector-76', 'noida-sector-101',
            'noida-sector-81', 'nse-sez', 'noida-sector-83', 'noida-sector-137',
            'noida-sector-142', 'noida-sector-143', 'noida-sector-144', 'noida-sector-145',
            'noida-sector-146', 'noida-sector-147', 'noida-sector-148', 'pari-chowk',
            'alpha-1', 'delta-1', 'gnida-office', 'depot-station'
        ]
    },
    {
        id: 'rapid', name: 'Rapid Metro', color: '#00AEEF',
        stations: [
            'sikandarpur', 'phase-2', 'belvedere-towers', 'cyber-city', 'moulesari-avenue',
            'phase-3', 'sector-42-43', 'sector-53-54', 'sector-54-chowk', 'sector-55-56'
        ]
    }
];
